### ISSUE TITLE
Android Beacon back button flow is inconsistent compared against Beacon for Web

### ISSUE THREAD

**Issue by shaunmcilroy** [helpscout/beacon-android-sdk-sample#100]
* Beacon version: 2.1.0

**Steps to reproduce**
1. On Beacon for Web start on the Ask tab, navigate to the Answers tab: https://c.hlp.sc/d5uWvz4X
2. Click Email, then press the back arrow: https://c.hlp.sc/2Nu5X21L
3. You'll be returned to the Ask tab
4. Follow the same process on Beacon for Android but instead of being returned to the Ask screen after pressing the back button, you're returned to the initial Answers tab instead. 

**Actual outcome**
Beacon for Android returns me to the initial loading screen based on the embed's current mode (Answers first)

**Expected outcome**
Beacon should have returned me to the previous "Ask" screen on Android, instead of the "Answers" tab

Internal tracking card: https://helpscout.atlassian.net/browse/ANDSDK-466

**Comment by scottyab** [comment]
hi, I'm pleased to mention we have fixed this issue as part of our 2.2.0 release. Please see the [changelog](https://github.com/helpscout/beacon-android-sdk-sample/blob/master/CHANGELOG.md) for full details. 

Please note there is a breaking change in 2.2.0, you will need to remove the reference to `beacon-core` from your Gradle dependencies (in your build.gradle file). To simplify things going forward we've merged `beacon-core` into the `beacon-ui` module. 

If you encounter any problems, please create a Github issue. 

Thanks,
Scott and mobile team @ Help Scout.

**Comment by sipersso** [comment]
I just updated to the 2.2.0 update and I have to say that I am very confused about the navigation. 

In this case there are three ways to navigate back and each take you to different destinations in the mobile app. 

1: The back button takes you one step up in the navigation hierarchy which is to "Ask"
2: The close button takes you back to the host app and closes the beacon. 
3: The "Return home" takes you back to the home of the beacon, which in this case is the "Answers"

![2 2 0](https://user-images.githubusercontent.com/6479433/91439459-47172580-e86d-11ea-809b-f176e9509993.png)

Is it really necessary to have all three? Android apps usually only have one back destination. If you compare to the web beacon only has a back button to the left, no x in the top right corner. And a close button at the bottom below the widget, which makes it a lot cleaner. 

The back button on the web takes you to "Answers", not "Ask". Personally I think this would make sense in the Android app too as you probably don't want to ask another question if you just asked one.

**Comment by sipersso** [comment]
Another point.... if you previous conversations you are taken to the previous conversations view. But if you press back you are taken to "Answers", so the back button behavior is not consistent.
