### ISSUE TITLE
Tapping on a Anchor links opens the link in a web browser rather than scrolling the article to the anchor

### ISSUE THREAD

**Issue by xiaohule** [helpscout/beacon-android-sdk-sample#101]
Hello,
With the latest Android SDK 2.1.1 on my Motorola phone running android 9 I have seen that the article section link behave differently than in the iOS SDK.

In iOS tapping on the hyperlink lead to the correct article section.
In Android, tapping on the hyperlink  opens the article in the phone web browser, and not even in the correct section.

**Steps to reproduce**
1. Create the following doc article

` <section class="index-list">`
`<h4>In this article</h4>`
`<ul>`
	`<li><a href="#0">Foo</a></li>`
	`<li><a href="#1">Bar</a></li>`
`</ul>`
`</section>`
`<h2 id="0">Foo</h2>`
`<h2 id="0">Bar</h2>`

2.In the android app containing the beacon, open the article and tap on Foo/BAr hyperlink

**Actual outcome**
The doc article is opened in the phone web browser

**Expected outcome**
We should be taken to the Foo/Bar section of the article in the app beacon

**Comment by aliripe** [comment]
Hi @xiaohule, thank you for the feedback!

I have created a test article with the content you provided – thank you! – and I have been able to reproduce this so I've created a ticket to track this. 
We will get in touch when we have a fix!

Internal tracking card: [ANDSDK-477](https://helpscout.atlassian.net/browse/ANDSDK-477)

**Comment by scottyab** [comment]
hi @xiaohule , I'm pleased to mention we have fixed this issue as part of our 2.2.0 release. Please see the [changelog](https://github.com/helpscout/beacon-android-sdk-sample/blob/master/CHANGELOG.md) for full details. 

Please note there is a breaking change in 2.2.0, you will need to remove the reference to `beacon-core` from your Gradle dependencies (in your build.gradle file). To simplify things going forward we've merged `beacon-core` into the `beacon-ui` module. 

If you encounter any problems, please create a Github issue. 

Thanks,
Scott and mobile team @ Help Scout.
