### ISSUE TITLE
How can I have the signature to pass into the method openSecureMode?

### ISSUE THREAD

**Issue by BinhTNT** [helpscout/beacon-android-sdk-sample#103]
Hello HelpScout support,

I'm trying to implement secure mode for Beacon on Android and iOS, but I'm not sure I understand how I can achieve it. I don't how I can have the signature to pass into the method BeaconActivity.openSecureMode.
The document recommended to store the computed signature on server, could you please show me the steps to do it? (in our case is PHP)

Another question, Is there a possibility to generate and store the secure mode signature in client side?

Beacon SDK version: 2.1.0

Thanks,
Binh

**Comment by aliripe** [comment]
Hi @BinhTNT!

We have a dedicated section that explains how to enable secure mode on the different platforms.

- [Web](https://developer.helpscout.com/beacon-2/web/secure-mode/) -> In here you'll learn about where you can find the `secret_key_from_beacon_config` and the steps you'll need to follow on the server-side to generate an HMAC signature. We have [PHP](https://developer.helpscout.com/beacon-2/web/secure-mode/#php) samples!
- [Android](https://developer.helpscout.com/beacon-2/android/#secure-mode)
- [iOS](https://developer.helpscout.com/beacon-2/ios/#secure-mode)

> Is there a possibility to generate and store the secure mode signature in client side?

Technically you *could*, but we recommend against embedding the `secret_key_from_beacon_config` on the client and retrieve the computed value from your server instead for security reasons. Once you fetch it, you could store it securely on the client using [`EncryptedSharedPreferences`](https://developer.android.com/reference/androidx/security/crypto/EncryptedSharedPreferences) in Android and the [Keychain](https://developer.apple.com/documentation/security/certificate_key_and_trust_services/keys/storing_keys_in_the_keychain) in iOS, or any other library/tool.

Let me know if this helps!

**Comment by BinhTNT** [comment]
Hi @aliripe 
Thanks for your response.
I read the document already, but I don't know how can I use window.Beacon in PHP? Where should I put the example code?
After client send API call to execute the example code in server:
window.Beacon('identify', {
//...
})
What should it return in response to client? Is it the signature string?
Sorry for I'm confusing about the usage of secure mode.

Thanks,
Binh

**Comment by scottyab** [comment]
Hey @BinhTNT 

> I don't know how can I use window.Beacon in PHP? Where should I put the example code?

Sorry for the confusion the PHP sample is a showing how you might generate the signature before returning Beacon JavaScript in an HTTP response that would be rendered as a Web page. 

Whereas I think when you mentioned PHP you mean from an API point of view? 

In essence, your PHP API needs to compute the `signature` and pass it back to the mobile app so it can then pass it to the SDK which in turn passes it to the Beacon API to be verified. 

To compute the `signature` use the user's email and Beacon secret key (that you keep on your secure server not in-app) using the [hash_hmac](https://www.php.net/manual/en/function.hash-hmac.php) with the sha256 hashing algorithm.  

In our Help Scout Android/iOS apps we pass the `signature` back as part of User details API call which we call as part of login process. We persist the `signature` so we have it ready to pass to the Beacon SDK via [BeaconActivity.openSecureMode()](https://developer.helpscout.com/beacon-2/android/#secure-mode) should the customer need to contact support team. 

Just to reiterate what @aliripe mentioned above please do not store the secret key or compute the signature in app. Thanks  

Let me know if that helps,

**Comment by BinhTNT** [comment]
Hi @scottyab 
Thank you for detailed instruction. I appreciate about that!

I have implemented Beacon identity in PHP. For the development, I hardcoded my email to generate the signature from PHP for testing (screenshot). But currently I have another issue, that is I could not restore "previous conversations" in secure mode. I'm pretty sure that there is no problem with my signature which computed by my back-end, because I used it for the sample app and it works well, I can see the "previous conversations" using my email and signature after I had several emails previously and re-installing the sample.
When I used it in my app (screenshot), it didn't work. I don't know what did I do wrong.

Could you please help us to investigate the issue?

Thanks,
Binh

<img width="849" alt="Screen Shot 2020-06-26 at 12 46 50 AM" src="https://user-images.githubusercontent.com/45462932/85774568-2a655100-b749-11ea-9106-4a9cb8cc694d.png">
<img width="785" alt="Screen Shot 2020-06-26 at 12 54 20 AM" src="https://user-images.githubusercontent.com/45462932/85774580-2e916e80-b749-11ea-86a0-fd3b6819fb9a.png">

**Comment by BinhTNT** [comment]
Hi @scottyab I hope you are doing well :) Could you please give us advise on our issue? Thanks

**Comment by scottyab** [comment]
Hey @BinhTNT 

I've recreated the issue your seeing with secure mode using the Android SDK I've created an internal ticket to address this ANDSDK-500. 

Thanks for flagging the with us. We'll update once the bug has been resolved. 
Thanks,
Scott

**Comment by scottyab** [comment]
Hey @BinhTNT today's release of 2.1.2 #112 fixes the secure mode issue you found. Thanks again for reporting this.
