### ISSUE TITLE
Hyperlinks in previous conversations are not clickable

### ISSUE THREAD

**Issue by xiaohule** [helpscout/beacon-android-sdk-sample#106]
With the Android SDK 2.1.0 when the support agent answers to a client with an helpscout article (or even a hyperlink to whatever web page), the client receives the title of the article as a static text (i.e. it is not clickable).

Is this an implementation error on our side or an issue in Android SDK 2.1.0?

* Beacon version:  2.1.0
* Android OS version: 9
* Device make/model: Moto G6

**Steps to reproduce**
1. send an article to answer a user question https://recordit.co/5cw1XNhLrX
2. open the "previous conversation" menu on the user device https://recordit.co/rtj8jMat9N
..

**Actual outcome**
The title of the sent article is not clickable

**Expected outcome**
The title of the sent article should be clickable (and open at best in the beacon, at worst in the device web browser)

**Comment by scottyab** [comment]
Hey @xiaohule thanks for raising this and including examples in the steps to reproduce. (However the recordit.co clips aren't working for me - they don't play.)

The good news is this issue has been fixed and will ship in version of 2.1.2 that's undergoing QA testing at the moment. 

We'll update this once we have released the fix. 

Thanks, 
Scott

**Comment by scottyab** [comment]
Hi @xiaohule today's release of 2.1.2 #112 resolves the issue you reported with hyperlinks not working in previous conversations. Thanks again for raising this.
