### ISSUE TITLE
Beacon history article links to an invalid Google Play page and not the help article

### ISSUE THREAD

**Issue by sipersso** [helpscout/beacon-android-sdk-sample#110]
Not sure if this is a bug in the Android SDK or in the HelpScout web interface, but I am reporting it here. 

1: A customer has read an article in the mobile beacon
2: The customer uses the beacon to reach out to customer support, 
3: "Beacon Information" shows links to the articles that the customer has read is shown in the HelpScout interface. 

Expected:
When pressing the link, I would expect to be taken to the help article that the customer has read. 

Actual:
I am taken to [https://play.google.com/store/apps/details?id=com.helpscout.beacon](https://play.google.com/store/apps/details?id=com.helpscout.beacon). This page doesn't even exist!

**Comment by hs-gv** [comment]
Hello @sipersso ,
Thank you for reporting.  Good find.  We have tracked it down to an Android SDK issue.  We'll create an internal issue and will discuss with the team further.

**Comment by scottyab** [comment]
hi @sipersso , I'm pleased to mention we have fixed this issue as part of our 2.2.0 release. Please see the [changelog](https://github.com/helpscout/beacon-android-sdk-sample/blob/master/CHANGELOG.md) for full details. 

Please note there is a breaking change in 2.2.0, you will need to remove the reference to `beacon-core` from your Gradle dependencies (in your build.gradle file). To simplify things going forward we've merged `beacon-core` into the `beacon-ui` module. 

If you encounter any problems, please create a Github issue. 

Thanks,
Scott and mobile team @ Help Scout.

**Comment by sipersso** [comment]
Just tried it out and I can confirm that this is fixed in 2.2.0 ;)
