### ISSUE TITLE
Glitchy UI when opening articles directly.

### ISSUE THREAD

**Issue by sipersso** [helpscout/beacon-android-sdk-sample#113]
I wanted to display a help article directly in one of my screens using BeaconActivity.open(myActivity, BeaconScreens.ARTICLE_SCREEN, arrayListOf("MyArticleId")), but when doing so I get a lot of visual glitches. 

Beacon version: 2.1.0

Steps to reproduce:
1. Call BeaconActivity.open(myActivity, BeaconScreens.ARTICLE_SCREEN, arrayListOf("MyArticleId"))

Actual outcome:
1: Beacon in full screen is flashing for a split second.
2:Beacon is closed, but the spinner remains.
3: Article is shown.

Expected outcome:
Article should be shown without visual artifacts. 

See attached video
[article_glitch.MOV.zip](https://github.com/helpscout/beacon-android-sdk-sample/files/5016626/article_glitch.MOV.zip)

**Comment by hs-gv** [comment]
Hello @sipersso , thanks for including the video, it does help clarify things.  We've created a ticket to discuss this improvement with the team further.  

Internal ticket ID: https://helpscout.atlassian.net/browse/ANDSDK-546

**Comment by aliripe** [comment]
@sipersso we've pushed a fix for this as part of the new Beacon 2.3.0 release. Please see the [changelog](https://github.com/helpscout/beacon-android-sdk-sample/blob/master/CHANGELOG.md) for full details.
