### ISSUE TITLE
Beacon.addPrefilledForm doesn't do anything if you have used it previously. 

### ISSUE THREAD

**Issue by sipersso** [helpscout/beacon-android-sdk-sample#114]
* Beacon version: 2.1.0

**Steps to reproduce**
1. Open a beacon and add a subject to a prefilled form with subject "Subject 1"
2. Close the beacon
3. Open a beacon again, but call Beacon.addPrefilledForm with another subject "Subject2"

**Actual outcome**
"Subject2" should be prefilled

**Expected outcome**
"Subject1" is prefilled and the second call to Beacon.addPrefilledForm is ignored. 

Looks like the prefill information is persistent and that I have to reinstall the app to get a chance to add another prefilled form.

**Comment by sipersso** [comment]
Looks like the info is cleared on send. But what if the user cancels and the info changes? Is there any way to make sure that the second call works?

**Comment by scottyab** [comment]
Hey @sipersso The second call to `Beacon.addPrefilledForm()` is not being ignored 😄  it will be updating the locally stored Prefill data. The issue you are describing is due to the way we prioritise the contact form data. We treat data that has been cached/entered by the user as a higher priority than prefill when rendering the contact form. 

If you want to prioritise the prefill data you can call `[Beacon.contactFormReset()](https://developer.helpscout.com/beacon-2/android/#resetting-the-contact-form)` before you call `Beacon.addPrefilledForm()` to ensure it's always using the latest prefill. 

Thanks for the question.  
Scott

**Comment by sipersso** [comment]
Hi Scott!

Thanks for the information about Beacon.contactFormReset(). I might be able to use this in certain cases. To clarify the bug report. In the sample above, the user did not enter anything at all and this made the API confusing. The documentation says that this information is cleared on send, but I didn't expect it to be persistent on cancel without user input.  Thanks for clarifying.

**Comment by sipersso** [comment]
@scottyab What is the difference between Beacon.prefilledFormReset() and Beacon.contactFormReset()?. The former doesn't seem to reset the prefilledForm, but the second one does.

**Comment by sipersso** [comment]
Another issue with the API. Since you don't get any activity results when starting the beacon (https://github.com/helpscout/beacon-android-sdk-sample/issues/81)  it is hard to clear the contact form when done. This means that if I add contact form info specific to where the user is in the app, I would have to always clear the information to make sure it isn't visible from anywhere else. 

The recommended way according to docs to get notified when the beacon is closed is to use a global listener in the application class, but that won't get you any information on where the contact form was shown and thus is hard to use to reset the form in certain conditions.

**Comment by scottyab** [comment]
>What is the difference between Beacon.prefilledFormReset() and Beacon.contactFormReset()?

`Beacon.prefilledFormReset()` - clears any previously prefill form data, where as `Beacon.contactFormReset()`  clears the draft we save from when the contact form screen is closed but not sent.  I think what you're seeing is still the same issue as mentioned previously  

For example on a fresh install or after a call to `contactFormReset()`. 
Add some prefill data via `Beacon.addPrefilledForm(..)` Then call `Beacon.prefilledFormReset()`. 
Now when you load the Contact form you should see no prefilled data. 

Maybe there is scope here for an improvement we missed? It would help to understand your use case a bit more can you explain what you are trying to achieve with these various different prefill configurations for the contact form. (if you'd pref to keep private please mail this help@helpscout.net)


> Beacon.contactFormReset() has no effect if the beacon is open when calling it.

Just curious how/what the usecase for calling this in the background is? It will clear the persisted from data but the screen is not listening for updates on that and will override when the screen is exited. It might actually cause issues as we weren't really expecting any Beacon API interaction like that when the user is "in" the SDK.

**Comment by sipersso** [comment]
Totally understand that you don't expect the API to be used in this way. However, the API currently does not offer any in the fragment when the beacon has completed, so I can't call Beacon.contactFormReset on done which would have  been more natural. 

I don't want to call it from the background, I just want to be able to attach a file to the help conversation when the customer is reaching out to support from a particular screen. In this screen it makes sense to send the attachment, but it doesn't make sense from anywhere else. 

What I want to do:
1: Open a beacon with a file attached to it from one screen in my app. 
2: Be able to open the beacon from another part of my app without attaching the file. 

To do this I need to call the Beacon.contactFormReset() between these calls, but when should I do it? The only way to get notified when the beacon is closed is via the beaconlistener, but this is done in the Application class and it doesn't provide any context. If I call reset here, it means that the beacon would always be reset even when I don't want this behavior. 

I have to confess that I am a bit confused about how prefill API works. So do I understand it correctly that the perfilledFormReset only works until you have shown the form?

**Comment by scottyab** [comment]
> So do I understand it correctly that the perfilledFormReset only works until you have shown the form?

I'm sure I understand the question, but let me try to explain how it's working and sorry the API is causing confusion. 

The `Beacon.prefilledFormReset()` will wipe/reset the prefilledForm when called. The Contact screen when it loads will read from the persisted storage to look for draft contact form if there's not one only then does it load the prefilledForm. Does that answer your question? 

Sounds like the feature request (#81) will solve this for you as it should offer some insight and allow you to configure the contact form more dynamically. Btw I agree it would be better to give more context on what has happened - thanks for the suggestion. In the meantime if not having the attached file there is a high priority to you over restoring the draft form data then as mentioned above call `Beacon.contactFormReset()` each time you open Beacon.

**Comment by sipersso** [comment]
Hmmm.. the prefilledFormReset doesn't have any effect if you have shown the form to the user. I guess that is the way you prioritize it, but I am not sure it makes sense if the user has not made any changes to the form.

If you do this:
1: Prefill the form
2: Let the user open the form and cancel with no changes.
3: Call Beacon.prefilledFormReset()
Then the form will not be reset since it will find a "draft". In this case I am not sure it makes sense to save the draft since the user hasn't entered anything. 

Yes, the #81 would be of great help here. If that was in place I could clear the attachement/prefill data when done on that particular screen. Since the API doesn't allow that yet, I opted to skip the beacon altogether in this case and just use email.

I know we have disagreements with state handling of the beacon since HelpScout views the beacon as if it was a separate app ( which would warrant persistent state and minimize/maximize behavior),  while I want to use it for context sensitive help as a part of the application flow and I see it as an extension of my app. 

For example I display the beacon from multiple places, each with different suggested articles and sometimes with attachements like this one. With the current minimize/maximize and persistent state, I feel that it is hard to know in which state the beacon will be in when I open it, making it hard to fit into the application. 

I think #81 could be the key to resolve a lot of these issues.

**Comment by scottyab** [comment]
I think the default behaviour of prioritising a draft over prefill is correct, however, you've raised a good point when the user cancels with no changes should we treat this as a draft? I think probably not as it's not a draft until the user has input something. I've raised an internal ticket for this https://helpscout.atlassian.net/browse/ANDSDK-553 - _Contact from: only save Draft state if the user has input/changed._ 

Thanks for providing the extra context.

**Comment by sipersso** [comment]
Thanks! Yes, that makes sense.

**Comment by aliripe** [comment]
Hey @sipersso, in the latest [Beacon 2.3.2 release](https://github.com/helpscout/beacon-android-sdk-sample/blob/master/CHANGELOG.md) and as discussed, we will only save the Draft state if the user makes changes.
