### ISSUE TITLE
Text cut off at bottom of releated Article after selecting rating the article

### ISSUE THREAD

**Issue by BinhTNT** [helpscout/beacon-android-sdk-sample#115]
In an article, after I select the emoji icon from "Did this answer your question", I notice that the text are cut off at bottom.

* Beacon version: 2.1.2

**Steps to reproduce**
1. Open an article
2. Select an emoji

**Actual outcome**
Text cut off at bottom in article

**Expected outcome**
Text should not be cut off a bottom

![hs_beacon_text_cut_off](https://user-images.githubusercontent.com/45462932/90044538-fa254200-dcf7-11ea-9f16-659a36c85723.png)

**Comment by scottyab** [comment]
Hey @BinhTNT, 

Thanks for mentioning this to us. The Article/related articles UI has been updated in the next release 2.2.0 as part of the fix for #101 and the related article text cut off you mention is no longer present 🎉  

We'll update this issue once the 2.2.0 has been released. Thanks!

**Comment by scottyab** [comment]
Hey @BinhTNT just RE-mentioning you as I've had to update the previous message and wanted to doubly check you'd seen it. Thanks

**Comment by BinhTNT** [comment]
Hi @scottyab Yeah I saw it. Thank you!

**Comment by scottyab** [comment]
Hi @BinhTNT Beacon Android SDK version [4.0.0](https://github.com/helpscout/beacon-android-sdk-sample/blob/main/CHANGELOG.md#version-400-2021-01-17) has addressed the last issue with cut off that you flagged. Please note the breaking changes that have been introduced partly to do with the update to target API 31 and AGP 7.x.x. 

Please let us know if we can be of further help.
