### ISSUE TITLE
Device specific crash when opening an article

### ISSUE THREAD

**Issue by BinhTNT** [helpscout/beacon-android-sdk-sample#116]
Hi Help Scout support,

Recently, our app has been reported a crash related to Beacon SDK on Android when user try to open an article.

Detail of crash:
_java.lang.IllegalStateException: Unable to create layer for BeaconArticleWebView, size 640x5120 max size 8192 color type 4 has context 1_

It seems like the issue happened on specific device, work fine on other ones. Could you please help us to investigate this issue?

Thanks,
Binh

* Beacon version: 2.1.0
* Android OS version: 9.0
* Device make/model: SM-J415FN

**Steps to reproduce**
1. Open Beacon
2. Access to an article

**Actual outcome**
App get crashed

**Expected outcome**
The app should open the article without crash

**Comment by scottyab** [comment]
Hi @BinhTNT  sorry to hear that, to confirm it's Samsung Galaxy J4 Plus? 

I've been searching and found a [similar crash](https://stackoverflow.com/questions/56690236/unable-to-create-layer-for-webview-size-640x7040-max-size-8192-color-type-4-has) listed on StackOverflow - which suggests moving the webview out of the scroll view resolves the issue. Coincidently this is exactly what we've done to solve the issue with anchor links #101 and will be part of 2.2.0. 

Are you able to recreate the crash? 

Thanks, 
Scott

**Comment by BinhTNT** [comment]
Hi @scottyab Yeah, it's Samsung Galaxy J4 Plus.

That's great to hear it will be solved in next release. We got the feedback from a user and got the stack trace from tracking. It's still stopping this user from access the articles. I have not tried to recreate the crash due to lack of device. It would be nice if the fix will be released soon.

Thanks,
Binh

**Comment by mehedihasan619** [comment]
@BinhTNT @jotaemepereira 
I just wanted to add that the crash is also reproducible on samsung SM-T387AA.

**Comment by scottyab** [comment]
hi @BinhTNT @mehedihasan619, I'm pleased to mention we have fixed this issue as part of our 2.2.0 release. Please see the [changelog](https://github.com/helpscout/beacon-android-sdk-sample/blob/master/CHANGELOG.md) for full details. 

Please note there is a breaking change in 2.2.0, you will need to remove the reference to `beacon-core` from your Gradle dependencies (in your build.gradle file). To simplify things going forward we've merged `beacon-core` into the `beacon-ui` module. 

If you encounter any problems, please create a Github issue. 

Thanks,
Scott and mobile team @ Help Scout.
