### ISSUE TITLE
Restrict orientation to portrait

### ISSUE THREAD

**Issue by SMJ93** [helpscout/beacon-android-sdk-sample#119]
* Beacon version: 2.1.2
* Android OS version: 10
* Device make/model: Pixel 3a

**Steps to reproduce**
1. Install SDK by following [docs](https://developer.helpscout.com/beacon-2/android/#requirements)
2. Launch chat and rotate your phone
3. Chat displays in landscape

I've used `android:screenOrientation="portrait"` for my other activities. Is there a way to restrict the beacon activity it to portrait?

**Comment by hs-gv** [comment]
Hello @SMJ93 ,

While we don't hear a lot of demand for orientation locking, and we develop and test the Android Beacon SDK to work in both portrait and landscape orientations, there should be a way to do this.  The Beacon SDK can be locked into the portrait orientation, but it is **unsupported**.  And since it is unsupported, there is the possibility that this may break with future releases of the SDK.  

Within your merged Manifest file, you should be able to add `screenOrientation="portrait"` to the Beacon activity that you would like to lock into portrait-only.

Let us know if you have any other questions.

**Comment by SMJ93** [comment]
Hi @hs-gv, thanks that worked! 

For anyone else who wants to do this just add the following to your AndroidManifest.xml (works with version `2.1.2`)

```
      <!-- Restrict all Help Scout Beacon activities to portrait-->
      <activity
        android:name="com.helpscout.beacon.ui.BeaconActivity"
        android:screenOrientation="portrait" />
      <activity
        android:name="com.helpscout.beacon.internal.presentation.ui.navigate.CustomNavigateActivity"
        android:screenOrientation="portrait" />
      <activity
        android:name="com.helpscout.beacon.internal.presentation.ui.home.HomeActivity"
        android:screenOrientation="portrait" />
      <activity
        android:name="com.helpscout.beacon.internal.presentation.ui.message.SendMessageActivity"
        android:screenOrientation="portrait" />
      <activity
        android:name="com.helpscout.beacon.internal.presentation.ui.article.ArticleActivity"
        android:screenOrientation="portrait" />
      <activity
        android:name="com.helpscout.beacon.internal.presentation.ui.conversations.ConversationsActivity"
        android:screenOrientation="portrait" />
      <activity
        android:name="com.helpscout.beacon.internal.presentation.ui.conversation.ConversationActivity"
        android:screenOrientation="portrait" />
      <activity
        android:name="com.helpscout.beacon.internal.presentation.ui.conversation.reply.ComposeReplyActivity"
        android:screenOrientation="portrait" />
      <activity
        android:name="com.helpscout.beacon.internal.presentation.common.FullScreenImageActivity"
        android:screenOrientation="portrait" />

      <activity
        android:name="com.helpscout.beacon.internal.presentation.ui.chat.ChatActivity"
        android:screenOrientation="portrait" />
```

**Comment by scottyab** [comment]
Thanks for sharing that @SMJ93 just to reiterate the ⚠️ that @hs-gv mentioned. Apart from `BeaconActivity` the others are internal activities which we could move/renamed/remove between version and any changes here wouldn't be flagged by us (as they are internal). 

That said we appreciate not every app can or wants to support landscape/switching orientation so I've logged a [support issue](https://helpscout.atlassian.net/browse/ANDSDK-567) to our backlog to add locking orientation officially to the SDK. We'll continue to monitor if we see it trend amongst developers we'll revisit and keep you updated.
