### ISSUE TITLE
Weird transition animation when exiting beacon

### ISSUE THREAD

**Issue by sipersso** [helpscout/beacon-android-sdk-sample#129]
Beacon version: 2.2.1

1. Open a beacon straight to the contact form (docs and chat disabled)
2. Close the beacon using the X button

Actual outcome:
When showing the beacon, I think this is done using the default transition. But when exiting, the beacon is using a slide out right animation. 

Expected:
If the beacon is shown using a default transition, it should be exiting using the same transition. 

Comment:
Slide out transitions are very uncommon in Android (Unless for the new SharedAxis animations), so I definitely don't think this is the right choice here. 

My guess is that you are using overridePendingTransactions in the contact activity to always use a slide out transition regardless of where the user came from. I don't think this is the right choice. See the attached video. 

[transition.MOV.zip](https://github.com/helpscout/beacon-android-sdk-sample/files/5200631/transition.MOV.zip)

**Comment by ScottPetit** [comment]
Hey 👋  @sipersso thanks for reporting this. We agree that the transition animation isn't ideal and have created an internal card to track it. We'll be in touch with more updates once we have them [ANDSDK-580](https://helpscout.atlassian.net/browse/ANDSDK-580).

**Comment by scottyab** [comment]
Hi @sipersso Beacon Android SDK version [4.0.0](https://github.com/helpscout/beacon-android-sdk-sample/blob/main/CHANGELOG.md#version-400-2021-01-17) has addressed this issue. Please note the breaking changes that have been introduced partly to do with the update to target API 31 and AGP 7.x.x. 

Please let us know if we can be of further help.
