### ISSUE TITLE
Return home button doesn't make sense if docs disabled

### ISSUE THREAD

**Issue by sipersso** [helpscout/beacon-android-sdk-sample#130]
Beacon version: 2.2.1

Steps to reproduce:
1: Open the beacon to the contact form (docs disabled, chat disabled)
2: Send an email

Actual results:
The "We're on it" screen is shown. There is a "Return home button present". Pressing return home will take you to the "Ask" screen, which doesn't make sense since this screen wasn't shown in the first place.

Expected results:
There should not be a "Return home" button that leads to a destination that the user has never been on. What does "home" mean in this case?

EDIT: Opening a separate issue for the back button state issues

**Comment by shaunmcilroy** [comment]
Hey @sipersso -- thanks for logging this. Just a quick touch on this to let you know we're going to chat with our designer and get back to you. We'll update soon!

**Comment by sipersso** [comment]
@shaunmcilroy Thanks! I do think it gets a bit much with the three back buttons on this screen, which each lead to different destinations. There is a back button, close button and a "Return Home" button.

To be honest I am not sure why this button even exist. Return home is not present in the web beacon, and not in the iOS beacon either so this seems to be Android only?

**Comment by ScottPetit** [comment]
Hey @sipersso, we're going to take a look at making some improvements with this and are tracking it internally [here](https://helpscout.atlassian.net/browse/MOBILE-398).  Thanks again for reporting it.

**Comment by sipersso** [comment]
Awesome! Thanks for looking into it @ScottPetit

**Comment by scottyab** [comment]
Hi @sipersso we’re not planning to remove this additional “return home“ button in the Android SDK at this time. We have a record of the request and will continue to track if more customers flag this issue and then reassess it. Thanks for the report.

**Comment by sipersso** [comment]
I wasn't expecting you to fix this since it hasn't been fixed in 1.5 years. Poor UX, but I guess that not that any use the beacon with docs disabled so I guess I understand why it is not important to you.
