### ISSUE TITLE
Beacon 2.2.1 crashes when opening BeconActivity with Live Chat entries

### ISSUE THREAD

**Issue by SecyWecy** [helpscout/beacon-android-sdk-sample#134]
The following error occurs when you open a Beacon Activity with an active live chat:

Caused by: java.lang.IllegalArgumentException: No enum constant com.helpscout.beacon.internal.data.remote.chat.ChatEventStatus.localOnly

**Comment by aliripe** [comment]
Hi @SecyWecy,

Thank you for reporting this issue, I've been able to reproduce it and I've created a ticket to track address it.

Ticket: [ANDSDK-584](https://helpscout.atlassian.net/browse/ANDSDK-584)

**Comment by aliripe** [comment]
Hi @SecyWecy, I'm pleased to report that we have fixed this issue as part of our Beacon 2.2.2 release. Please see the [changelog](https://github.com/helpscout/beacon-android-sdk-sample/blob/master/CHANGELOG.md) for full details.
