### ISSUE TITLE
Not possible to see long text in contact form

### ISSUE THREAD

**Issue by sipersso** [helpscout/beacon-android-sdk-sample#135]
I got a message from my customer complaining about not being able to write a long support ticket. After trying it out, I could easily see that there is a usability issue when writing long support emails. See attached screenshot.

**Beacon version:** 2.2.1

**Steps to Reproduce**
1: Open the email contact form. 
2: Write a long email covering more than 4-5 lines

**Actual outcome**
Text field seems to be fixed height and only take up a small portion of the screen, which makes it very hard for the user to read and write longer texts. 

**Expected outcome**
The text field should take up as much room as possible, so that the user can read/write long texts. 

**Screenshots or GIFs**
![tiny_textfield](https://user-images.githubusercontent.com/6479433/93742776-05209b80-fbef-11ea-829e-15a6c0b3c50e.jpg)

**Comment by sipersso** [comment]
FIY: Just finished reading through my support inbox today and it seems like most of them are complaining about this issue.

**Comment by aliripe** [comment]
Hi @sipersso,

Thank you for the report! I was able to reproduce this and I've created a ticket internally to keep track of it.

**Ticket:** [ANDSDK-585](https://helpscout.atlassian.net/browse/ANDSDK-585)

**Comment by aliripe** [comment]
Hi there @sipersso, I'm happy to report that we've added improvements to the user experience when starting a new conversation and replying to it as part of our Beacon 2.2.2 release that should fix this issue. 

Please, check out the [changelog](https://github.com/helpscout/beacon-android-sdk-sample/blob/master/CHANGELOG.md) for full details.
