### ISSUE TITLE
Infinite spinner in poor network connections (State restoration issue)

### ISSUE THREAD

**Issue by sipersso** [helpscout/beacon-android-sdk-sample#138]
I got this bug report from a customer of mine and he can reproduce it in his basement, that has a poor internet connection. For my application, poor network connections are pretty common as many use the apps while in a basement or similar.

This is the original error report I got:
"When I leave the app having the feedback section opened and reopen the app it opens a blank white screen. Force closing the app brings me back to the home screen."

Then a few minutes later:
"I've got an update: this happens only with bad connection. With good connection the feedback section loads properly. But by pressing the back button the whole app closes without going to the apps home screen. Only by reopening it in getting back to the apps homescreen"

After testing the app out in the simulator I can see that the app is not handling poor network connectivity correctly after state restoration and I think this is what my user is talking about. 

Steps to reproduce (on Android Simulator):
1: Open a beacon with docs enabled //This is needed to ensure you have cached docs for the beacon
1: In simulator settings, disable wifi and set the signal strength to none in the connection settings. 
2: Enable don't keep activities. This will trigger state restoration on next when we resume the app, like my customer did. 
3: Open a beacon, with docs enabled. Just like in step one. You will now see a spinner, but cached docs will show in a couple of seconds. 
4: Open another app.
5: Switch back to the beacon. 

Expected result:
The beacon should show handle poor network connections gracefully. Just like in step 3 where it shows cached docs after 3 seconds. 

Actual result: 
An infinite spinner is shown. Since there is no back button on the screen, my user thought the only way to exit was to force close the app. I have tried and confirmed that the physical back button works, but it definitely appears like there is no way to exit.

**Comment by jotaemepereira** [comment]
Hey, @sipersso thanks for the feedback. I was able to reproduce the issue you are describing, I've created this [ticket](https://helpscout.atlassian.net/browse/ANDSDK-592) in our internal tracking system for our team to check and we will let you know when it gets fixed. Thanks 🙌

**Comment by scottyab** [comment]
Hi @sipersso we are closing this issue as we were not able to replicate it as a user. We were able to replicate it using the Don’t Keep Activities Enabled option; however, that’s a developer-only setting. Should your users continue to experience this, we recommend hitting back and reopen the Beacon. Please do let us know if you experience this more often without that setting enabled.

**Comment by sipersso** [comment]
When you start having problems when the "Don't keep activities" option is enabled, it means that you don't handle state restoration properly. So this was more a way of telling you that you have an architecture problem and steps for you to reproduce it (with the developer setting enabled), so you could fix the actual issue (state is not restored properly).

It is causing problems in poor networking connection, but if you have state restoration issues you may also get all sorts of weird crashes and other problems. Too bad you chose not to fix this when I provided you with step by step instructions on how to reproduce the issue.
