### ISSUE TITLE
Send button is small and very hard to see

### ISSUE THREAD

**Issue by sipersso** [helpscout/beacon-android-sdk-sample#140]
I did some usability testing today on a user that was not familiar with my app. One of the tasks was to send a support email. 

The user could not see the send button. It is very small and also has a disabled color until you have filled in subject/message/email. 

I think the reason that the send button is small is because that it is inside a toolbar above the keyboard and you don't wan the toolbar and attach images to be bigger. But it is very easy to miss. It doesn't even look like a button in disabled state. I definitely think this something worth doing usability testing for.

This behavior also differs from the iOS app where the "Send a Message" button, not only is more clear since it is text based, but it is also enabled at all times. 

If you look at the screenshots for iOS, Android and web you will see that the "Send a message" button is enabled on the other platform and it is also a lot easier to see as it is text based and bigger.

![android](https://user-images.githubusercontent.com/6479433/95214951-b7ac4d00-07f0-11eb-9f9d-465d81c17ff8.png)
![ios](https://user-images.githubusercontent.com/6479433/95216372-440b3f80-07f2-11eb-96e2-5e16418812da.jpeg)

<img width="354" alt="web" src="https://user-images.githubusercontent.com/6479433/95216566-82086380-07f2-11eb-993f-7012ed63dd56.png">

**Comment by aliripe** [comment]
Hey @sipersso, we've tweaked the send button on the latest [Beacon 2.3.2 release](https://github.com/helpscout/beacon-android-sdk-sample/blob/master/CHANGELOG.md). It now looks like this:
[<img src="https://user-images.githubusercontent.com/7792150/105030848-acee8e80-5a54-11eb-9c0e-56d26f9b26cb.jpg" width="320">](https://user-images.githubusercontent.com/7792150/105030848-acee8e80-5a54-11eb-9c0e-56d26f9b26cb.jpg)

It should be easier to see now. Do let us know what you think!
