### ISSUE TITLE
com.helpscout.beacon.internal.presentation.ui.article.ArticleActivity ArticleId cannot be null

### ISSUE THREAD

**Issue by BinhTNT** [helpscout/beacon-android-sdk-sample#142]
Hello,
I would like to report a specific device crash.

Beacon SDK: 2.2.1
Device model: Nexus 4
Android OS version: 6.0.1

Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{mayappid/com.helpscout.beacon.internal.presentation.ui.article.ArticleActivity}: java.lang.IllegalArgumentException: ArticleId cannot be null
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2419)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2479)
       at android.app.ActivityThread.-wrap11(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1347)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:148)
       at android.app.ActivityThread.main(ActivityThread.java:5421)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

Actual outcome
Beacon crash

Expected outcome
Beacon should not crash

Thanks,
Binh

**Comment by scottyab** [comment]
Hey @BinhTNT, I'm keen to understand how you're using the SDK API. Is this reproducable? What steps lead to the error?  

As you might of guessed from the stack trace ArticleActivity requires a ArticleId, this is passed via intent extras when opening the screen. It cannot be opened another way. I wonder if there has been some issue with the intent extra being lost after process death or similar 🤔 . Keen to hear more information before deciding to remove our `requireNotNull(articleId)` check.

**Comment by scottyab** [comment]
Isssue #141 is a duplicate noting the same issue with intent extra data being lost on the same old device (nexus 4) with URL on `FullScreenImageActivity`

**Comment by BinhTNT** [comment]
Hi @scottyab We have found the crash from our users via Firebase report. The number of affected users is not much. I'm not sure it is still happening with our users, just wondering to report in order your team to see if any risks from the issue.

I also could not reproduce the crash. I attached the code how I'm using the SDK in java android, note that our project is React Native, so it would be much different. Hope it would be helpful. 
Thanks

[java.zip](https://github.com/helpscout/beacon-android-sdk-sample/files/5376910/java.zip)

**Comment by scottyab** [comment]
I've reviewed your code thanks for sharing. In `public void openArticle(String articleId)` you may want to replace your `if(arrList.size() > 0)` check with a is `null` or empty check on the `articleId`  and not call `BeaconActivity.open()` to the  BeaconScreens.ARTICLE_SCREEN unless `articleId` has a value.   

That said I don't think this is the underlying issue that caused the stack trace as you've reported the nearly the same crash on FullScreenImageActivity. These crashs would occur if the user of this Nexus 4 trying to call these activities directly - which is techinically possible via the adb activity manager or 3rd party app. I think we should close this for now and reopen if you see it occuring more often and on more devices.
