### ISSUE TITLE
com.helpscout.beacon.internal.presentation.ui.message.SendMessageActivity}: java.lang.IllegalStateException: KoinApplication has not been started

### ISSUE THREAD

**Issue by BinhTNT** [helpscout/beacon-android-sdk-sample#143]
Hello,

I would like to report a crash issue. The stack trace as below:

Fatal Exception: java.lang.RuntimeException: Unable to instantiate activity ComponentInfo{myappid/com.helpscout.beacon.internal.presentation.ui.message.SendMessageActivity}: java.lang.IllegalStateException: KoinApplication has not been started
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2846)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3042)
       at android.app.ActivityThread.-wrap14(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1639)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6780)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1500)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1390)

* Beacon version: 2.2.1
* Android OS version: 7.0
* Device make/model: Samsung Galaxy Tab S2

**Actual outcome**
Beacon get crashed

**Expected outcome**
Beacon should not crash

Thanks,
Binh

**Comment by scottyab** [comment]
Hey @BinhTNT thanks the crash stack trace. I'm correct in understanding this is via crash reporting? Can you help us understand how many times this has occurred and the number of users it's effecting?

On the surface, I don't understand how the KoinApplication cannot be started as it's the first thing we check/initalise in the onCreate() of any of the internal BeaconActivities such as SendMessageActivity.

**Comment by BinhTNT** [comment]
Hi @scottyab There are 5 crashes and affecting 2 users.

**Comment by codenameDuchess** [comment]
Thanks for providing these details @BinhTNT and sorry for the trouble. We've created an [internal ticket](https://helpscout.atlassian.net/browse/ANDSDK-604) to track this issue. If there are any additional reproduction steps you can provide we'd appreciate it.

**Comment by shaunmcilroy** [comment]
Hi @BinhTNT would it be possible to get any information on how to reproduce this crash? In order for our team to be able to fix the reported issue we need clear steps for them to follow — without additional information we will close out this issue until further reports are made and reproduction steps become available.

Look forward to your response.

**Comment by shaunmcilroy** [comment]
Hi @BinhTNT as per the above message we are closing this issue until steps to reproduce the reported behaviour are provided. Please update the issue if you're able to provide those steps and we'll reopen and investigate. Thanks.
