### ISSUE TITLE
App is closed unexpectedly after opening contact form directly, go back and close Beacon

### ISSUE THREAD

**Issue by BinhTNT** [helpscout/beacon-android-sdk-sample#144]
Hello,
I have found an issue of SDK 2.2.2. After opening contact form directly, then I go back by clicking on back arrow, next I close Beacon by clicking on "X" button. I notice that app is closed unexpectedly.

* Beacon version: 2.2.2

**Steps to reproduce**
1. Open contact form directly
2. Click on back arrow button to go back
3. Click on "X" button to close Beacon
4. Notice that app is closed instead of Beacon

**Actual outcome**
App is closed unexpectedly instead of closing Beacon

**Expected outcome**
App should not be closed

Here is the video of issue: https://drive.google.com/file/d/1VVsXwPMeEtyCjNgWQF1RCeR8ch6ipJ2_/view?usp=sharing

Could you please help to investigate it?
Thanks,
Binh

**Comment by shaunmcilroy** [comment]
Hi @BinhTNT this is the same issue we have logged under https://github.com/helpscout/beacon-android-sdk-sample/issues/131

We'll close this issue and keep you in the loop on that card. As per our earlier requests please check the board for existing bug reports ahead of filing new instances — that way we can continue to group them all together.

Thanks!
