### ISSUE TITLE
Beacon SDK silently disables Firebase ad tracking

### ISSUE THREAD

**Issue by GrahamBorland** [helpscout/beacon-android-sdk-sample#146]
**Technical details**

- Beacon version: 2.2.2
- Android OS version: any
- Device make/model: any
- Impacted user count: a huge number

**Actual outcome**

Beacon disables Google ad tracking in client apps.

**Expected outcome**

Beacon should not silently disable ad tracking in client apps.

**Steps to reproduce**

1. Have an app which relies on google_analytics_ad tracking.
1. Verify your app works correctly and Firebase `sign_up` conversion events are working as expected.
1. Add a dependency on the Beacon SDK. You don't need to call any Beacon code; just adding the dependency is sufficient.
1. Notice that your Firebase events no longer work. 

**Screenshots/Screen Recording**

BEFORE adding Beacon dependency.

![image](https://user-images.githubusercontent.com/5768767/99423700-bcd4df80-28f8-11eb-8918-66fbdbcfa34a.png)

AFTER adding Beacon dependency. Notice that the `sign_up` event is no longer being tracked as a special conversion event (green icon); it's now just a regular event (blue icon).

![image](https://user-images.githubusercontent.com/5768767/99423730-c3635700-28f8-11eb-8e5c-01d32688c9a3.png)

**Additional Information**

The fix is to forcibly override the Beacon manifest entry which disables tracking.
    
```xml
        <meta-data
            android:name="google_analytics_adid_collection_enabled"
            android:value="true"
            tools:replace="android:value" />
```

This behaviour should have been clearly documented, and the fix provided, in the Beacon documentation. We only tracked it down after hours of frustrating debugging.

**Comment by jotaemepereira** [comment]
👋 Hey @GrahamBorland, thanks for the report. We disabled Google Analytics in the past because it was on by default, and we didn't want to force users to opt-in when they did not want to due to GDPR restrictions. 

As you said, we should have been more explicit about it in our documentation. Sorry for all the time we made you lost debugging the issue 😓. We are going to update our documentation to reflect this.

**Comment by scottyab** [comment]
Hey @GrahamBorland just a quick update on this. We've investigated this today and found we no longer need to depend on Firebase Core (who's dependency included Firebase Analytics). We're still testing this but from the looks of things, we shouldn't need the `google_analytics_adid_collection_enabled` meta-data going forward 🎉. Thanks again for raising this.

**Comment by aliripe** [comment]
Hey @GrahamBorland, we've pushed a fix for this as part of the new Beacon 2.3.0 release. Please see the [changelog](https://github.com/helpscout/beacon-android-sdk-sample/blob/master/CHANGELOG.md) for full details.

**Comment by GrahamBorland** [comment]
Thank you!

**Comment by sipersso** [comment]
Great job identifying this issue @GrahamBorland! I haven't been able to figure out why my Firebase Attribution hasn't been working for a long long time.... I guess this is the explanation.
