### ISSUE TITLE
Embedded videos not loading when viewing an article

### ISSUE THREAD

**Issue by NappyPirate** [helpscout/beacon-android-sdk-sample#147]
When viewing an article that contains a video loaded via an iframe, such as vimeo, the video is not displayed.

**Technical details**

- Beacon version: 2.2.2
- Android OS version: 11 (API level 30)
- Device make/model: Pixel 4 XL Emulator, Pixel 2 device
- Impacted user count: All

**Actual outcome**

    No video is visible when viewing an article that contains a video.

**Expected outcome**

    Video should be visible and responsively sized like the web experience.

**Steps to reproduce**

    1. Create an article that contains a vimeo video
    2. Open Beacon
    3. View the article that contains the video

**Additional Information**

    This regression appears to have occured between 2.1.2 and 2.2.2.

**Comment by scottyab** [comment]
Hey @NappyPirate can you send over the Beacon Id and the article Id you're seeing this issue occur. help@helpscout.com (FOA mobile team). Thanks

**Comment by NappyPirate** [comment]
@scottyab I just sent the requested information over in an email to help@helpscout.com.  Some further information, I have recreated the issue with this sample project and it is occuring in the emulator as well as on my physical device.

**Comment by hs-gv** [comment]
@NappyPirate  just wanted to confirm we received the information.  We'll investigate further and let you know what we find.

**Comment by codenameDuchess** [comment]
Hi @NappyPirate 👋 Just wanted to follow up and let you know that we've had a chance to address this issue and will let you know once the fix is live. Thanks for reporting it and providing the details we needed to track it down.

[Internal Tracking Link](https://helpscout.atlassian.net/browse/ANDSDK-633)

**Comment by scottyab** [comment]
Hey @NappyPirate we've just released regression fix for the video embed issue you found in 2.3.1. Thanks again for reporting this. Please do let us know if you have any further questions. Scott
