### ISSUE TITLE
Messages from Android don't include useful device info

### ISSUE THREAD

**Issue by GrahamBorland** [helpscout/beacon-android-sdk-sample#149]
**Technical details**

- Beacon version: 2.3.0
- Android OS version: Any
- Device make/model: Any
- Impacted user count: All of them

**Actual outcome**

Beacon did not include useful device metadata (OS version, device type, etc.) in a chat message from Android. These fields are all blank.

![image](https://user-images.githubusercontent.com/5768767/100871177-bb2e1e80-3497-11eb-9913-25f63e1f564b.png)

**Expected outcome**

Beacon should include this metadata. For example, this metadata is provided when sending a chat from iOS.

![image](https://user-images.githubusercontent.com/5768767/100871314-00eae700-3498-11eb-940f-3ccf6dfaa309.png)

**Steps to reproduce**

1. Send a chat from Android 
1. Look for useful technical info in the incoming chat.
1. Observe that the data is missing.

**Comment by shaunmcilroy** [comment]
Hey @GrahamBorland thanks for filing the issue -- we're investigating this after receiving a report from your colleague Ben and will pass an update along here with more information when available.

**Comment by codenameDuchess** [comment]
Hi @GrahamBorland, thanks for raising this issue and sorry for the trouble. We'll circle back when we've had a chance to address this and let you know once a fix has been released. 

In the meantime, as a potential work around, you can add your own [session attributes](https://developer.helpscout.com/beacon-2/android/?_ga=2.189995438.405143960.1606852401-840331068.1606852401#session-attributes) via the `Beacon.addAttributeWithKey(..)` method. 

They'll show up beneath the "Session Information" section as shown in [this screenshot](https://user-images.githubusercontent.com/404105/66761582-30a5ec80-ee9c-11e9-9c84-ea4fb0d17fe1.png).

Thanks again!

[Internal Tracking Ticket](https://helpscout.atlassian.net/browse/MOBILE-472)

**Comment by adrianne-helpscout** [comment]
Closing out as changes were released today that should have addressed the issue. No need to update the SDK as the change impacted an internal service.
