### ISSUE TITLE
Opening contact form directly makes secure mode not working

### ISSUE THREAD

**Issue by BinhTNT** [helpscout/beacon-android-sdk-sample#150]
Hello Help Scout support,

I notice that there is an issue with contact form in secure mode that exists for many versions of Beacon SDK. When user opens contact form directly, then sends a message, it will always be basic mode on Beacon support. It also cannot load previous messages in this case. I don't see where to pass the signature when opening contact form directly via method
**BeaconActivity.open(this.reactContext, BeaconScreens.CONTACT_FORM_SCREEN, new ArrayList<String>());**
which might cause the issue.

- Beacon version: 2.3.0

**Actual outcome**

    Beacon could not send message in secure mode and load previous messages

**Expected outcome**

    Beacon should send message in secure mode and load previous messages

**Steps to reproduce**
1. Make sure secure mode works fine and try to open contact form directly
2. Send a message
3. Notice that it will always be basic mode in Beacon support instead of secure.
    
Could you please help?

Thanks,
Binh

**Comment by scottyab** [comment]
Hey @BinhTNT, sorry it's not clearer from the docs, there's a specific method for opening in secure mode. ` BeaconActivity.openInSecureMode(@NotNull Context context, @NotNull String signature,
        BeaconScreens screen, ArrayList<String> args)`. Please see the note in the docs [here]( BeaconActivity.openInSecureMode). 

Closing this based on the above, however if you are still seeing an issue please reopen and let us know. Thanks, Scott

**Comment by BinhTNT** [comment]
Hi @scottyab It works, thank you for providing correct method. But It sill have an issue that the previous conversation button is not visible. Is it a bug?

Please see the screenshot
![Screenshot_20201209-142715](https://user-images.githubusercontent.com/45462932/101598736-34df8280-3a2b-11eb-95a8-2008d226018d.png)
