### ISSUE TITLE
Previous conversation is invisible when opening contact form directly in secure mode

### ISSUE THREAD

**Issue by BinhTNT** [helpscout/beacon-android-sdk-sample#151]
Hello,

When user open contact form directly in secure mode using

    BeaconActivity.openInSecureMode(@NotNull Context context, @NotNull String signature,
        BeaconScreens screen, ArrayList<String> args)

Then back to Ask screen, notice that the previous conversation button is not visible to user

- Beacon version: 2.3.0

**Actual outcome**

    Beacon did not show previous conversation button in Ask screen

**Expected outcome**

    Beacon should show previous conversation button

**Steps to reproduce**

    1. Make sure secure mode works well with identified email which had previous messages already, open contact form directly
    2. Press back arrow, then press Ask tab
    2. Notice that the previous conversation is not visible in Ask screen

**Screenshots/Screen Recording**
![Screenshot_20201209-142715](https://user-images.githubusercontent.com/45462932/102040544-ae96b800-3dff-11eb-80b4-157a0b0c55b6.png)

Thanks,
Binh

**Comment by aliripe** [comment]
Hi @BinhTNT!

Thank you for reporting this and adding the repro steps. I've been able to reproduce it and I've created a ticket to address it. We'll keep you posted.

Internal ticket: [ANDSDK-636](https://helpscout.atlassian.net/browse/ANDSDK-636)

**Comment by aliripe** [comment]
Hey @BinhTNT, we've pushed a fix for this as part of the new Beacon 2.3.2 release. Please see the [changelog](https://github.com/helpscout/beacon-android-sdk-sample/blob/master/CHANGELOG.md) for full details.
