### ISSUE TITLE
Problem report: Conversation history for a beacon contains messages from two different mailboxes

### ISSUE THREAD

**Issue by nikos-houssos-feel** [helpscout/beacon-android-sdk-sample#158]
**Technical Details:**

- SDK version: 2.3.1
- Android OS version: 10
- Impacted user count: Everyone

**Actual outcome**

    Conversation history for beacon1 contains both the messages exchanged with mailbox1 (beacon1) and the messages exchanged with mailbox2 (beacon2).

**Expected outcome**

    Conversation history for beacon1 should contain the messages exchanged with mailbox1 (beacon1).

**Steps to reproduce**

    1…A mobile user has two beacons (beacon1, beacon2), each associated with a different mailbox (mailbox1, mailbox2). Mailbox1 and mailbox2 are each associated with a separate Helpscout account/mailbox.
    2…The user sends a message through beacon1 (mailbox1).
    3…The user sends a message through beacon2 (mailbox2).
    4…The user goes to conversation history for beacon1.

**Comment by codenameDuchess** [comment]
Hi @nikos-houssos-feel 👋 

Thank you for reporting this issue, and sorry for the trouble. I've opened an [internal tracking ticket](https://helpscout.atlassian.net/browse/ANDSDK-650) for us to investigate.  We will let you know once we've had a chance to address it and get a fix into a release.

**Comment by nikos-houssos-feel** [comment]
Thank you @codenameDuchess 
Any estimate on when this fix is foreseen to make it into a release is very welcome. We need this for serving certain customer deployments.

**Comment by adrianne-helpscout** [comment]
👋 @nikos-houssos-feel and anyone else following along, internally we are tracking this as a single issue. It will be easier if we have just a single conversation. Let's do that over [on the issue that you raised in the IOS SDK repo](https://github.com/helpscout/beacon-ios-sdk/issues/152). But, we'll leave this issue open here so that everything is easily discoverable.
