### ISSUE TITLE
Migrate away from JCenter

### ISSUE THREAD

**Issue by GrahamBorland** [helpscout/beacon-android-sdk-sample#159]
I'm sure you're well aware of this already, but we've got until May to migrate the Android SDK artifacts from JCenter to Maven Central.

https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/

**Comment by ScottPetit** [comment]
Yea @GrahamBorland, we're working on figuring out next steps and will be sure to update this issue when we've migrated off JCenter.

**Comment by scottyab** [comment]
Here's the internal tracking [issue](https://helpscout.atlassian.net/browse/ANDSDK-652) for this.

**Comment by aliripe** [comment]
Hi @GrahamBorland, 

We're pleased to report that we've successfully migrated the Beacon SDK to Maven Central.

In the process, we've changed the `artifactId` from `beacon-ui` to `beacon` so please, make sure that you update your `build.gradle` file to match this change:
```
repositories {
    mavenCentral()
    …
}
dependencies {
    implementation "com.helpscout:beacon:3.0.0"
}
```

**Comment by GrahamBorland** [comment]
@aliripe Thanks for doing this.

The new artifact on Maven Central is still referring to Koin on Jcenter, though.

```
  > Could not find org.koin:koin-core:2.2.1.
     Required by:
         project :app > com.helpscout:beacon:3.0.0
```

Koin has recently updated their group id from `org.koin` to `io.insert-koin` when they moved to Maven Central, so it looks like Beacon need to update its Koin dependency before Beacon is truly free of JCenter.

https://github.com/InsertKoinIO/koin#latest-version-

**Comment by scottyab** [comment]
ah, thanks @GrahamBorland. We'll investigate!
