### ISSUE TITLE
Error RepositoryInstance

### ISSUE THREAD

**Issue by Cballini** [helpscout/beacon-android-sdk-sample#16]
* Beacon version: 0.2.4
* Android OS version: 7.1.2
* Device make/model: Redmi 4X

**Steps to reproduce**
I tried to call Beacon.getRepositoryInstance()

**Actual outcome**
An error occured : "beacon Id must be set". 

**Expected outcome**
My beacon Id isn't empty, I see in fuction getRepositoryInstance() that there is that code : 
 if (isEnabled()) {
            throw new SDKInitException("beacon Id must be set");
        }
instead of : 
 if (!isEnabled()) {
            throw new SDKInitException("beacon Id must be set");
        }

**Comment by scottyab** [comment]
Hey @Cballini, Thanks for flagging this and diagnosing the issue 👍. We'll ensure that fix is in the next release.

**Comment by scottyab** [comment]
Closing as fixed in 0.2.5. Please shout if there are any issues.
