### ISSUE TITLE
Contact Form is not getting reset after sent

### ISSUE THREAD

**Issue by rekhaagarwal** [helpscout/beacon-android-sdk-sample#163]
Thank you for taking the time to submit an issue with the details requested below. Our engineering team actively monitors issues submitted to this repo and will generally respond within 2 business days.

**Please note the following:**

- **Please ensure you are testing on the latest version of the SDK ahead of submitting a report.**
- **All reports are required to include steps to reproduce any issues reported.** 
- **Issues logged without this information may be closed until more information is made available.**

**Technical details**

- Beacon version: 2.3.3
- Android OS version: 10
- Device make/model: One Plus
- Impacted user count: All

**Actual outcome**

We are calling Beacon in Normal Mode. 
BeaconActivity.open(context);
Every time we **sent** the form ( in ask tab), next time its showing previous field name and email even we are calling **contactFormReset**() / **prefilledFormReset**() before BeaconActivity.open(context);

**Expected outcome**
Next time, The email and name should not be auto populated from previous entry

**Screenshots/Screen Recording**

 Video attached

https://user-images.githubusercontent.com/21167009/111059899-f1c7fc00-84be-11eb-96dd-f00a7749cf3f.mp4

**Comment by aliripe** [comment]
Hi @rekhaagarwal,

Thank you for the detailed bug report and the video, they have helped me understand the issue and I've been able to reproduce this locally.

I've created a ticket for the team to look at it and we will get back to you when we have more information!

**Ticket:** [ANDSDK-660](https://helpscout.atlassian.net/browse/ANDSDK-660)

**Comment by rekhaagarwal** [comment]
Thanks @aliripe

**Comment by rekhaagarwal** [comment]
Hey @aliripe any update on same?

**Comment by shaunmcilroy** [comment]
Hi @rekhaagarwal - Shaun hopping in for @aliripe. We don't have an update on this issue at this time. Should there be any future updates in an upcoming release we'll update you here on this thread.

Cheers!

**Comment by scottyab** [comment]
Hi @rekhaagarwal Beacon Android SDK version [4.0.0](https://github.com/helpscout/beacon-android-sdk-sample/blob/main/CHANGELOG.md#version-400-2021-01-17) has addressed this issue. Please note the breaking changes that have been introduced partly to do with the update to target API 31 and AGP 7.x.x. 

Please let us know if we can be of further help.
