### ISSUE TITLE
Full-screen button for an embedded YouTube video is disabled

### ISSUE THREAD

**Issue by ksilz** [helpscout/beacon-android-sdk-sample#165]
**Technical details**
- Beacon version: com.helpscout:beacon-ui:2.3.3
- Android OS version: Android 10, 2021-02-01, OOWW_2_290_SP05
- Device make/model: Nokia 5.3
- Impacted user count: 50

**Actual outcome**
The full-screen button for an embedded YouTube video is disabled. When playing the video, it remains in its original size which is too small.

**Expected outcome**
The full-screen button for an embedded YouTube video is enabled on Android. When playing the video, it automatically switches to full-screen and changes into the right orientation, as it does on iOS.

**Steps to reproduce**
1. Follow [the advice to embed a YouTube video in an article](https://docs.helpscout.com/article/56-add-responsive-video-to-a-docs-article). Please note that the particular video here has no sound:

```
<section class ="video widescreen"> 
<iframe src="https://www.youtube.com/embed/qVYNzd6Kszc" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe> 
</section>
```

2. View the article through the beacon on an Android phone.

**Screenshots/Screen Recording**

Here's the article with the video in a beacon on Android. Notice the **disabled** full-screen button:
![Help Scout Android YouTube](https://user-images.githubusercontent.com/1061209/113215099-48c92180-9272-11eb-9fdf-ede618cfed74.png)

**Additional Information**
If I open [this URL to the same article](https://yhigh-mobile.helpscoutdocs.com/article/16-team-member-sign-in) on the same Android phone in a browser, then the full-screen button is **enabled**. So it seems to me that the HTML code to embed the video is correct in general. It's just that the WebView you're using in the beacon is somehow not configured for full-screen view:

![Screenshot_20210331-224551~2](https://user-images.githubusercontent.com/1061209/113215981-96925980-9273-11eb-8dd3-8cbe4ddb6876.png)

**Comment by jotaemepereira** [comment]
@ksilz Thanks for the report! We were able to reproduce this issue and we created an internal [ticket](https://helpscout.atlassian.net/browse/ANDSDK-665) to discuss with the team. We will let you know when we have news about this.
