### ISSUE TITLE
`showGetInTouch` doesn't have any effect anymore

### ISSUE THREAD

**Issue by guillaume-tgl** [helpscout/beacon-android-sdk-sample#169]
I've just upgraded from v1.0.6 to v3.0.1 of your SDK 😅
I'm globally satisfied with the changes except for one detail: I set `showGetInTouch` to false and previously, this would basically force users to make a search and/or view an article before contacting us.
Now, it seems like this option has no effect as the Ask tab is always present, no matter the value of this option.

Am I missing something or is this option useless now? And is there a way to hide the Ask tab?

**Comment by scottyab** [comment]
Hey @guillaume-tgl 

> is there a way to hide the Ask tab?

Yes! Sounds like you're looking for the Beacon mode [here's a link](https://developer.helpscout.com/beacon-2/mobile/customize/#beacon-mode) to screenshot examples of how the Beacon home screen changes depending on Mode. By your description you'll want `SELF_SERVICE` you can either set this on the Beacon in Help Scout or use the local override as noted [here](https://developer.helpscout.com/beacon-2/android/#settings-customization) in the Android SDK docs

Also we're happy to see a long term SDK user make the jump to the latest version of the SDK 🎉.  Version 2 was the big increment with the addition of real-time Chat and migration to Android X. Version 3 was smaller but as we were moving away from Bintray and changing the artefact Id we took the decision to increment the major version. Hope that helps provide some extra context. 

Let me know if self service Beacon mode is what you're after, cheers, Scott

**Comment by scottyab** [comment]
Thanks for flagging `showGetInTouch` I think we missed removing this option from the SDK and docs as it's effectively been replaced with Beacon Mode.

**Comment by guillaume-tgl** [comment]
Thanks!
