### ISSUE TITLE
Nothing happens when click on message icon, so cant send another message.

### ISSUE THREAD

**Issue by s-gagandeep** [helpscout/beacon-android-sdk-sample#17]
* Beacon version: 0.2.4
* Android OS version:7.0(occurring on all version)
* Device make/model: Motorola/G5 plus (occurring on all devices)

**Steps to reproduce**
1. Call  BeaconActivity.open(context);
2. Construct message and send.
3. Unable to click on Message Icon, so can't send another message.
..

**Actual outcome**
Unable to click on Floating Chat button, if I already send 1 message, so I can't
![helpscout](https://user-images.githubusercontent.com/24538769/46737795-139f7200-ccba-11e8-97b5-1b259a1d51f8.png)
 send another message.

**Expected outcome**
 Message icon should be clickable.

**Screenshots or GIFs**

**Comment by scottyab** [comment]
Hi @s-gagandeep Thanks for raising this. We actually caught this too and have fixed it in v0.2.5 which is planned for release later this week. I'll update this PR to confirm 0.2.5 released.

**Comment by s-gagandeep** [comment]
@scottyab thanks!! waiting for 0.2.5.

**Comment by scottyab** [comment]
Closing as fixed in 0.2.5. Please shout it there's any issues.
