### ISSUE TITLE
Close button (X) shows help scout home screen twice if once any option chat or email used.

### ISSUE THREAD

**Issue by jash612** [helpscout/beacon-android-sdk-sample#171]
Thank you for taking the time to submit an issue with the details requested below. Our engineering team actively monitors issues submitted to this repo and will generally respond within 2 business days.

**Please note the following:**

- **Please ensure you are testing on the latest version of the SDK ahead of submitting a report.**
- **All reports are required to include steps to reproduce any issues reported.** 
- **Issues logged without this information may be closed until more information is made available.**

**Technical details**

- Beacon version: 3.0.1
- Android OS version: 10
- Device make/model: Mi A2
- Impacted user count: -

**Actual outcome**

Home Screen shown twice on close button.

**Expected outcome**

    Beacon should close.

**Steps to reproduce**

1. Go to help scout
2. Use email option
3. Send some message
4. Press return to home
5. Press close button (X) on top right corner of help scout home screen

**Screenshots/Screen Recording**

https://recordit.co/EojfaTBb0N

**Additional Information**

No crash.

**Comment by jotaemepereira** [comment]
Hey @jash612 thanks for the report. I was able to reproduce the issue you are experiencing, I've created an internal [ticket](https://helpscout.atlassian.net/browse/ANDSDK-671) for the team to work on and we will let you know when it is live.

**Comment by scottyab** [comment]
Hi @jash612 Beacon Android SDK version [4.0.0](https://github.com/helpscout/beacon-android-sdk-sample/blob/main/CHANGELOG.md#version-400-2021-01-17) has addressed this issue. Please note the breaking changes that have been introduced partly to do with the update to target API 31 and AGP 7.x.x. 

Please let us know if we can be of further help.
