### ISSUE TITLE
Invalid signature

### ISSUE THREAD

**Issue by krobert** [helpscout/beacon-android-sdk-sample#175]
Hey,

I sent this question on the website help chat and they forwarded me here.
This is not a sdk issue, but a technical question.

Im receiving this error when im trying to accesss beacon:
{"code":401,"status":"UNAUTHORIZED","message":"Invalid signature","correlationId":"25fcfac5-02f0-4b9f-a104-6064072a6372#63352658"}

Platform: android 
Build type: debug
Version and phone and these information are not relevant.
We have different apps for different countries, others are working, but one of them is not. 

The signature is generated by our api, we are using the same on iOS and Android.

Is this related to the apk signature? If yes, where can we setup debug signature?
On the website i can't see any options in the app settings, nothing in the android documentation.

Any other issue that we can check to fix this issue would be really helpfull.
Thanks

**Comment by scottyab** [comment]
Hey @krobert, 

It's not related to apk signature but I can see how it's not 100% clear. It's the signature param that is passed to Beacon API as an HTTP header when using Support history security (Beacon secure mode). Here's a screenshot of the Beacon settings screen where this is enabled.  
![Image 2021-07-12 at 9 36 41 am](https://user-images.githubusercontent.com/404105/125256846-bf0b0480-e2f4-11eb-89a1-44f43f29819d.jpg) and [Help Scout Docs article](https://docs.helpscout.com/article/1229-support-history-security-options).

Also [here's a link](https://developer.helpscout.com/beacon-2/android/#secure-mode) to our Android SDK docs that mentions how to open a Beacon in secure mode and pass your computed signature to the SDK.   

`BeaconActivity.openInSecureMode(context, "Your computed signature goes here");`

> We have different apps for different countries, others are working, but one of them is not.

* Are you using the same Beacon and signature for each of the different apps? 
* Could you post the code you're using to launch the Beacon is it the same in each app? (You're welcome to email is to help@helpscout.com FOA mobile team if you prefer)

Thanks

**Comment by krobert** [comment]
Hey, thanks for the quick answer.

> Also [here's a link](https://developer.helpscout.com/beacon-2/android/#secure-mode) to our Android SDK docs that mentions how to open a Beacon in secure mode and pass your computed signature to the SDK.
> `BeaconActivity.openInSecureMode(context, "Your computed signature goes here");`

I'm passing the signature like its mentioned in the documentation. 
Every supported country have different beacon id and i guess the signature is calculated with that id, so it must be different. I checked the available settings, the beacon id correct, the signature is coming from backend, so i can only guess whats wrong, but the strange thing is, that this is working on iOS. We are using the same api calls, the beacon for this country have the same id on both plaforms.

> * Could you post the code you're using to launch the Beacon is it the same in each app?

Sorrry about the code formatting, i cant get it work correctly.
At app start i set it up:

`
val overrides = BeaconConfigOverrides(
        chatEnabled = true, messagingEnabled = true, color = "#2C2431"
)
Beacon.setConfigOverrides(overrides)
Beacon.Builder().withBeaconId(beaconId).let {
    if (BuildConfig.DEBUG) {
        it.withLogsEnabled(true)
    } else it
}.build()
`

Clicking on the support button (the email and signature is never empty i checked, just some legacy code) 

`
fun goToHelpScoutPage(helpScoutSignature: String, fullName: String, email: String) {
    Beacon.addPreFilledForm(PreFilledForm(subject = "..."))
    Beacon.addAttributeWithKey("Version", AppUtil.getAppVersion(this))
    Beacon.addAttributeWithKey("Model", AppUtil.getModel())
    Beacon.identify(email, fullName)
    BeaconActivity.openInSecureMode(this, helpScoutSignature)
    overridePendingTransition(0, 0)
}
`

**Comment by scottyab** [comment]
>Every supported country have different beacon id and i guess the signature is calculated with that id

The signature will be different for each Beacon even if the email of the user is the same. As the signature should be computed (SHA-256 HMAC) using the email and Beacon's Secure Key (from the  Support history security section of the Beacon settings). 

>but the strange thing is, that this is working on iOS

My first assumption was that the `helpScoutSignature` is incorrect/invalid. But something doesn't add up here 🤔 if you're seeing a Beacon/User/Signature working on one platform and not another then we might have a bug in the SDK. It's not clear to me why it works for some Beacons and not others. 

@krobert We can try and rule this out but I need the following params to test and debug this. I suggest emailing them to help@helpscout.com FOA mobile team. Thanks! 

* Beacon Id, email and signature for a Beacon that's working on iOS and Android
* Beacon Id, email and signature for the problematic Beacon that's working on iOS but not Android. 

With these details, we can plug them into the simple Kotlin Sample app [here](https://github.com/helpscout/beacon-android-sdk-sample/tree/master/sample-kotlin) and verify and recreate what you are seeing and then dig deeper.

**Comment by krobert** [comment]
@scottyab hey, after some investigation, it turned out backend was not using the correct country ids for generating the signature.
Ios did a fallback to the other one, this is why it was working.
So the issue is resolved on our side, thanks for your help :D

**Comment by scottyab** [comment]
Great news! Do let us know if there's anything else we can help with.
