### ISSUE TITLE
Out-of-Date Beacon ID Instructions 

### ISSUE THREAD

**Issue by klinker24** [helpscout/beacon-android-sdk-sample#24]
* Beacon version: 0.2.6
* Android OS version: 9.0.0
* Device make/model: Pixel 3

**Issue description**

> You can find your Beacon ID by logging into Help Scout and navigating to the Beacon you'd like to use. Inside the Installation section you'll see an Android tab which highlights the Beacon ID and a code snippet.

I have tried to obtain my beacon ID using the steps on this repo, but they don't seem to be accurate. There is no way for me to "navigate to the Beacon you'd like to use", so I cannot get to the "Installation section". This is the page I have that contains my Beacons: 

![screen shot 2018-11-18 at 7 30 48 am](https://user-images.githubusercontent.com/4874287/48673231-f05fb200-eb04-11e8-83d0-96aecc9b7679.png)

Clicking the Beacon does not do anything.

**Actual outcome**

I attempted to use the "Form ID" as the "Beacon ID". It even has the same format, but it just results in an error on the `BeaconActivity`:

![device-2018-11-18-073414](https://user-images.githubusercontent.com/4874287/48673174-5d267c80-eb04-11e8-96bf-d8b97fc04dfb.png)

This is the form ID that I am attempting to use, from that page. 

```
cefa328c-e90b-11e8-ab20-0ee9bb0328ce
```

I am fine sharing it here, because I can just generate a new beacon and delete the old one.

**Expected outcome**

Show the help topics and give the user access to the "Get in touch" button, as it does with the sample Beacon ID, from the README.

![device-2018-11-18-073641](https://user-images.githubusercontent.com/4874287/48673203-b7274200-eb04-11e8-9104-b7e0b3bf4696.png)

**Comment by scottyab** [comment]
Hey @klinker24, Looks like that screen is for the Beacon v1. You'll need to create a v2 Beacon. 

* Go to Manage>Beacons (http://c.hlp.sc/408b0e81fdd0), then select one of the Beacons you've created (or create a new one). 
* You should get a screen like this http://c.hlp.sc/4180d0f576bc This is the screen for our Beacon called "Android Beacon" which is used in  our Android HelpScout App. 
* From there click the Installation link (in the left menu) and then on Android tab shown here http://c.hlp.sc/778d51b3f5d5. 

If you need further help please drop us an email help@helpscout.com 

I'll create a task to improve the docs to include this info. 

Thanks, Scott

**Comment by klinker24** [comment]
Ahh, I see. Thank you!
