### ISSUE TITLE
Add ability to pre-attach a file

### ISSUE THREAD

**Issue by guillaume-tgl** [helpscout/beacon-android-sdk-sample#34]
This is a feature request (unless I'm missing it): I would like to be able to attach a file by default to the user request. The iOS SDK seems to allow it (https://developer.helpscout.com/beacon-2/ios/#swift-5) but i couldn't find this feature in the Android one.

**Comment by scottyab** [comment]
Hey @guillaume-tgl thanks for raising the issue. You are correct attachment prefill on Android isn't available yet but @jotaemepereira recently finished adding this and we hope to have it in a release soon.  I'll leave this issue open and we'll update once it's in the release.

**Comment by jotaemepereira** [comment]
@guillaume-tgl We added a fix for this on the newest [release](https://github.com/helpscout/beacon-android-sdk-sample/blob/master/CHANGELOG.md).

You can check the developer [page](https://developer.helpscout.com/beacon-2/android/#pre-filling-contact-form) on how to add it.

Let us know any question!

**Comment by guillaume-tgl** [comment]
Thanks a lot!
