### ISSUE TITLE
Name isn't added to the contact form

### ISSUE THREAD

**Issue by taaeng** [helpscout/beacon-android-sdk-sample#37]
* Beacon version: 0.2.9
* Android OS version: Android Pie
* Device make/model: Pixel 3

**Steps to reproduce**
1. Launch the BaconActivity with email and name
2. Tap "Contact"

**Actual outcome**
User have to input username

**Expected outcome**
Users name is allready set 

**Screenshots or GIFs**
<img width="540" alt="device-2019-01-19-125930" src="https://user-images.githubusercontent.com/1119881/51426424-e6ccf600-1bea-11e9-9bd0-106b09a93875.png">

**Code**
Beacon.Builder().withBeaconId(...).build()
Beacon.login(email, fullName)
BeaconActivity.open(activity)

**Comment by scottyab** [comment]
Hey @taaeng, Thanks for the report, we'll look into the issue with the name passed to the Beacon login method. 

In the meantime please try the prefilled form way of setting contact form data as shown in the [sample-customisation](https://github.com/helpscout/beacon-android-sdk-sample/blob/master/sample-customisation/src/main/java/net/helpscout/sample/beacon/CustomisationActivity.java#L93). 

Or like this... 
```kotlin
Beacon.addPreFilledForm(PreFilledForm("Scott"))
```

**Comment by jotaemepereira** [comment]
@taaeng We added a fix for this on the `0.3.0` [version](https://github.com/helpscout/beacon-android-sdk-sample/blob/master/CHANGELOG.md). Thanks!
