### ISSUE TITLE
Add more theme customization

### ISSUE THREAD

**Issue by guillaume-tgl** [helpscout/beacon-android-sdk-sample#43]
It would be really great to be able to customize other colors than the primary color: primary dark color (the one used for status bar), accent color, primary text color...

**Comment by jotaemepereira** [comment]
Hey @guillaume-tgl, we added this feature request to our internal roadmap, thanks for the feedback

**Comment by jotaemepereira** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Override PrimaryDark color](https://trello.com/c/WBNoYVkN/397-override-primarydark-color)

**Comment by jotaemepereira** [comment]
Hey @guillaume-tgl after some discussion with the team, we decided to add this card to our long term backlog. So we are not going to work on this pretty soon, we will let you know if this changes in the near feature. Thanks!

**Comment by jotaemepereira** [comment]
Hey @guillaume-tgl, after some discussion with the team, we decided to add this card to our long-term roadmap. We have a few updates we'd like to get through ahead of this so I'm afraid it won't be in development in the near future, but we'll definitely let you know if our plans change down the road. Thank you so much for your feedback, please let us know if there's anything else we can help with!

**Comment by sipersso** [comment]
I noticed that the HelpScout app uses white text color for the tand and toolbar instead of the black color I get from the SDK(2.1.0). Yet I can’t find a setting for it. Do you have one or has this been changed in the SDK?

**Comment by jotaemepereira** [comment]
> I noticed that the HelpScout app uses white text color for the tand and toolbar instead of the black color I get from the SDK(2.1.0). Yet I can’t find a setting for it. Do you have one or has this been changed in the SDK?

Hey @sipersso, sorry for the slow response on this. We missed this comment. Can you open a new ticket with this bug you are seeing? So we can track it differently for this customization request. We appreciate it!

**Comment by sipersso** [comment]
> > I noticed that the HelpScout app uses white text color for the tand and toolbar instead of the black color I get from the SDK(2.1.0). Yet I can’t find a setting for it. Do you have one or has this been changed in the SDK?
> 
> Hey @sipersso, sorry for the slow response on this. We missed this comment. Can you open a new ticket with this bug you are seeing? So we can track it differently for this customization request. We appreciate it!

No worries, I submitted a new issue here: https://github.com/helpscout/beacon-android-sdk-sample/issues/111

**Comment by scottyab** [comment]
We're not looking to add this level of theme customisation in the near term. I'm closing this issue to as part of our housekeeping to keep the open issues list the concise. Thanks for the suggestion.
