### ISSUE TITLE
Ability to customize style of articles

### ISSUE THREAD

**Issue by guillaume-tgl** [helpscout/beacon-android-sdk-sample#45]
It would be really great to be able to use a custom style sheet to customize how articles are displayed by the Beacon SDK.
It would allow for example to change the font type, color of links, size of headers to match our app style... We already use a custom stylesheet for our Docs website so an equivalent for mobile SDK would be awesome :)

**Comment by jotaemepereira** [comment]
Hey, @guillaume-tgl sorry for keep you waiting on this. 

Unfortunately, this feature is not our scope right now because there are a bunch of accessibility concerns around allowing customers to tweak their Beacon colors, links, etc. outside of what we provide in the Beacon builder

We will let you know if something changes in the future! Thanks for the feedback.

**Comment by jotaemepereira** [comment]
You can find more custsomization documentation [here](https://developer.helpscout.com/beacon-2/ios/#settings-customization) and[ here ](https://developer.helpscout.com/beacon-2/ios-api/Classes/HSBeaconSettings.html). 

Let us know of any question!

**Comment by guillaume-tgl** [comment]
@jotaemepereira We still have a need for this feature but for one more reason: we'd like to have articles that have different sections for Android and iOS and we'd like to show only sections that are relevant for the current device. Please tell me this is something you will consider 🙏. Otherwise, we'll have to stop using the SDK and use your API directly to show articles 😭

**Comment by shaunmcilroy** [comment]
Hi @guillaume-tgl, Shaun here hopping in for @jotaemepereira. At the moment we don't have any immediate plans to allow visual customization of articles with Beacon, either serving custom CSS via the SDK or our JS for web implementation. In the meantime it may be more beneficial if you talk directly to the API for documentation, and keep Beacon available for Chat and Contact form functionality. If this changes at any point in the future we'll let you know!

**Comment by guillaume-tgl** [comment]
Thanks for the answer.
