### ISSUE TITLE
Device orientation not handled correctly

### ISSUE THREAD

**Issue by guillaume-tgl** [helpscout/beacon-android-sdk-sample#46]
* Beacon version: 0.3.0
* Android OS version: 9
* Device make/model: Galaxy S9

**Steps to reproduce**
1. Launch the Beacon Sample Kotlin
2. Rotate the device in landscape mode
3. Tap on Open Beacon button

**Actual outcome**
Beacon opens in landscape mode but immediately rotates to portrait

**Expected outcome**
Beacon should open in landscape mode

**Comment by jotaemepereira** [comment]
Hey @guillaume-tgl! We are going to start supporting orientation changes on the next version `0.3.1`. We will let you know as soon is out. Thanks!

**Comment by scottyab** [comment]
Thanks for the feedback, this is resolved with v0.3.1.
