### ISSUE TITLE
Connecting to beacon

### ISSUE THREAD

**Issue by switters1** [helpscout/beacon-android-sdk-sample#52]
Thank you for taking the time to submit an issue with all the details shown below. Our engineering team monitors issues submitted and strives to respond with 1-2 business days.

* Beacon version: BN001, sticker, nrf51822
* Android OS version: 8.1
* Device make/model: BLU Vivo XL5

**Steps to reproduce**
1. Load beacon android sdk master onto phone via visual studio
2. Run Sample Core 
3. Run sample custimisation
..

**Actual outcome**
Sample core keeps stopping
Sample custimasation "There was a problem retrieving data from server" 

**Expected outcome**
Beacon should run apps and connect to beacon.  All good with eBeacon from google play.

This newbie understands that this may not be the best place to get started. Perhaps there is a newbie forum?

**Comment by scottyab** [comment]
Hey @switters1, more than happy to help. Just to double check have you added your BeaconId [here](https://github.com/helpscout/beacon-android-sdk-sample/blob/master/sample-core/src/main/java/com/helpscout/beacon/sample/core/CoreApplication.kt#L8) Also with `Beacon.loggingEnabled(true)` you should see the URLs and HTTP error codes that would be useful to help understand what request is struggling to get data from the server. 

Thanks

**Comment by scottyab** [comment]
Also if you wanted to communicate more privately that Github issue then please feel free to email help@helpscout.com and we'll continue the conversation there. Thanks

**Comment by switters1** [comment]
Hey scotty, yes the Beacon ID is entered.

**Comment by scottyab** [comment]
I've resolved issue with crash on core-sample with #53. We are continuing the conversation about Beacon loading issues via Help Scout. Thanks
