### ISSUE TITLE
Unable to change email for non logged in user

### ISSUE THREAD

**Issue by sipersso** [helpscout/beacon-android-sdk-sample#67]
* Beacon version:  1.0.8
* Android OS version: -
* Device make/model: -

**Steps to reproduce**
1. Start a beacon without being logged in.
2. Enter an invalid email and press send
3. Open the beacon again, now change the email to the correct one. 
..

**Actual outcome**
Email will be sent to the invalid email from step 2

**Expected outcome**
If you enter an email to the email field this email should be used for the conversation. 

Logging the user out after sending a message is not good either because it prevents the user from retrieving previous conversations. I always want the user to be able to edit the email adress since I can't rely on that they are using the same email adress for their app account as they are using for sending and replying to emails. 

The Android SDK also differs from the iOS SDK here as the iOS SDK is behaving as expected

**Comment by sipersso** [comment]
The initial description was invalid. The iOS SDK is behaving as expected, but not the Android SDK

**Comment by sipersso** [comment]
Updated the issue to make it more clear what is happening.

**Comment by scottyab** [comment]
Thanks @sipersso for flagging this. I've created issue on our internal tracker to investigate/fix.  
https://helpscout.atlassian.net/browse/ANDSDK-230

**Comment by scottyab** [comment]
Hi @sipersso, just a quick update on this. We've merged a fix that'll ensure that when the user updates the email address in the contact form we use the updated email address.  This will be included in the next SDK release. I'll leave this issue open until the release is published. Thanks for your patience.

**Comment by sipersso** [comment]
Awesome! Thank you :)

**Comment by scottyab** [comment]
Hi @sipersso thanks again for spotting this. This has been fixed as part of the 2.0.0-beta release.
