### ISSUE TITLE
Avoid exposing extensions on Android library classes

### ISSUE THREAD

**Issue by sipersso** [helpscout/beacon-android-sdk-sample#70]
Beacon version: 1.0.8

In the class com.helpscout.beacon.internal.extensions.AndroidExtensions.kt, the visibility of the extensions should not be public. If they are public, that means that they will be visible to all consuming apps. 

For example. As a consumer of the library I don't want to have access to HelpScouts internal extensions on the view class (like hide(), invisible(), show() etc).

**Comment by jotaemepereira** [comment]
@sipersso Thanks for catching this. I've created a ticket on our internal tracking system to work on this. I will let you know once we have more news about this issue. Thanks!

Issue: https://helpscout.atlassian.net/browse/ANDSDK-245

**Comment by scottyab** [comment]
Fixed in version 2.0.0. Will close once released. Thanks.

**Comment by scottyab** [comment]
2.0.0 released -> https://bintray.com/helpscout/beacon
