### ISSUE TITLE
HelpScout 2.0.0-beta doesn't compile, could not find com.commonsware.cwac.document

### ISSUE THREAD

**Issue by sipersso** [helpscout/beacon-android-sdk-sample#73]
Upgraded from 1.0.9 and now my project fails to compile with 

* What went wrong:
Could not determine the dependencies of task ':app:buildDebugPreBundle'.
> Could not resolve all task dependencies for configuration ':app:debugRuntimeClasspath'.
   > Could not find com.commonsware.cwac:document:0.4.1.
     Searched in the following locations:
       .....
      .....
     Required by:
         project :app > com.helpscout:beacon-ui:2.0.0-beta

I guess the repository url "https://s3.amazonaws.com/repo.commonsware.com" has to be added to the gradle configuration. If so, this should be added to the documentation?

**Comment by scottyab** [comment]
Hey @sipersso wow you're quick on the reactions! thanks! We'll look to make this repo not a requirement. In the mean time check out this diff to the https://github.com/helpscout/beacon-android-sdk-sample/blob/965d994a87baeda8db6fdba86b2e34587a689ce6/build.gradle for the workaround.

**Comment by jotaemepereira** [comment]
I've added a task for our team to track this in our internal system: https://helpscout.atlassian.net/browse/ANDSDK-250

**Comment by sipersso** [comment]
Yeah, I wanted to try out the new beacon :)

The beta seems very buggy though. I opened a few additional tickets.

//Simon

**Comment by scottyab** [comment]
Hi, This has been addressed in 2.0.0 so developers no longer have to add the repo "https://s3.amazonaws.com/repo.commonsware.com". Thanks again for mentioning this @sipersso I'll close this issue once 2.0.0 is released

**Comment by scottyab** [comment]
2.0.0 released -> https://bintray.com/helpscout/beacon
