### ISSUE TITLE
If you change the email used you loose conversation history.

### ISSUE THREAD

**Issue by sipersso** [helpscout/beacon-android-sdk-sample#74]
Beacon version: 2.0.0-beta

1.  Open beacon and send a message (docs disabled, normal mode)
2. Close the beacon
3: Open the beacon again and send a message, but enter a different email adress this time

..
Expected:
Both the messages from 1 and 3 should be shown in message history.
Actual:
Only the message from step 3 is visible.

Seems to be the same behavior on both iOS and Android. This is not obvious to the end user and there is no way to get to the previous conversations on the old email.

**Comment by sipersso** [comment]
This is related to https://github.com/helpscout/beacon-android-sdk-sample/issues/67. The reason why this is a problem is that if a user enters an invalid email adress and then changes it, then it would be good if the conversation history was still visible in the beacon. If not, when customer supports responds the conversation will just be lost.

Another reason is that people might have many email adressess and not remember which one they used in the last conversation or want to change it for some other reason. That doesn't mean that they want to delete the messages in the conversation history.

**Comment by scottyab** [comment]
Hey @sipersso I'm checking in with Web team to confirm this behavour. I'll let you know the outcome.

**Comment by sipersso** [comment]
Not sure if the web and mobile SDKs should behave the same here. I mean if you are not logged in. On the web, you might not expect your messages to still be there? But on mobile, it is not clear to the user that it will loose conversation history by specifying a different email adress. I would expect my messages to still be there. 

Now, you could argue that I should use the secure mode and always have users logged in instead and I would do that if it was possible for the user to specify the email adress, but this field is hidden in authenticated mode, which is a bit strange, especially now with social logins and anonymous logins with relay email adresses like Sign In With Apple.

**Comment by scottyab** [comment]
Hi @sipersso with a basic mode Beacon that relies solely on the user adding or updating their email address via the Beacon contact form, there is no support for allowing previous conversations to be reconciled if the email address changes. The main reason for this is we key off the email. 

You could switch to a Secure mode Beacon, then if the User's email changed you'd update it
* In Help Scout web app
* In the Beacon via `Beacon.login(email)` and pass new signature (as it's based on the email) to `BeaconActvitiy.openInSecureMode(context, newSignature)`.

After this, the user should see their previous conversations from the old email address. 

This kind of conversation would be best suited to email, if you'd like to contiune please drop us an email at Help@helpscout.com Thanks.

**Comment by sipersso** [comment]
You have mail.
