### ISSUE TITLE
Glitchy UI when opening beacon with docs disabled without a previous conversation

### ISSUE THREAD

**Issue by sipersso** [helpscout/beacon-android-sdk-sample#75]
* Beacon version: 2.0.0-beta

**Steps to reproduce**
1. Perform a clean install so you don't have conversation history 
2. Open the beacon in normal mode, docs disabled

Expected outcome:
The beacon should be opened with a nice transition.

Actuall outcome:
1:  A white screen with a spinner is shown
2: The white screen is closed and a progressbar is shown in the middle of the screen for a split second.
3:  The contact screen is shown with a back button that shouldn't be there in the top left corner. (You have an open ticked on this already)

**Comment by hs-gv** [comment]
Hello Simon,
Thanks for reporting this.  Just to clarify, you have docs disabled?  The reason I ask is because the title of the issue has "docs enabled", while the steps mention "docs disabled".

**Comment by sipersso** [comment]
Sorry about that. Changed the title. This Is when docs is disabled

**Comment by hs-gv** [comment]
Thanks for the clarification.  Let me attempt reproducing the issue with the steps you provided.

**Comment by scottyab** [comment]
Hey @sipersso thanks for the feedback I've logged this internally as ANDSDK-262. We're planning a revamp of the UI and take into account Beacon modes. This issue will be addressed as part of that work.

**Comment by scottyab** [comment]
Hi, We're busy working on the revamp of the UI but we squeezed this fix into 2.0.2 that was released today. Thanks again for flagging. 

Just to note due to updating OKHttp, Beacon 2.0.2 requires Java 1.8 Source and target compatibility, encase you see a `java.lang.NoSuchMethodError` after update.

**Comment by sipersso** [comment]
@scottyab good job! Thanks for fixing this
