### ISSUE TITLE
internal logging extensions are visible to consumers of the library

### ISSUE THREAD

**Issue by sipersso** [helpscout/beacon-android-sdk-sample#77]
* Beacon version: 2.0
**Steps to reproduce**
1.  In the consuming library write d { "My Log"} 
2. Try to import d.
..
**Actual outcome**
Autocomplete suggests a number of internal HelpScout functions

**Expected outcome**
Only my own "d" function should be visible. HelpScout internals should not be public 

**Screenshots or GIFs**
![Skärmavbild 2019-12-12 kl  10 36 34](https://user-images.githubusercontent.com/6479433/70700596-4d5b7680-1ccb-11ea-9c62-3ac4858c3cce.png)

This is not a major issue, but still. I believe that these details should be hidden if possible.

**Comment by hs-gv** [comment]
Thanks for reporting. Let me pass this along to the team.

**Comment by hs-gv** [comment]
Will be creating an issue to reduce the visibility of these functions later, but the priority will be low.  Sorry we can't really provide an ETA for this.  However, there is a workaround you can apply to your IDE to reduce what autocomplete shows you, here is the link: https://www.jetbrains.com/help/idea/auto-completing-code.html#exclude.  Thanks again for bringing this to our attention.
