### ISSUE TITLE
Definition lists not correctly styled

### ISSUE THREAD

**Issue by guillaume-tgl** [helpscout/beacon-android-sdk-sample#82]
Thank you for taking the time to submit an issue with all the details shown below. Our engineering team monitors issues submitted and strives to respond with 1-2 business days.

* Beacon version: 1.0.6
* Android OS version: 9
* Device make/model: Galaxy S9

**Steps to reproduce**
1. Open an article with definition lists

**Actual outcome**

Here is what we see in the Android Beacon

![Screenshot_20200206-140411_Genius Scan](https://user-images.githubusercontent.com/2244170/73939532-f5677780-48e9-11ea-81b7-5b11c79f501b.jpg)

**Expected outcome**
Here is how it appears on our website: https://help.thegrizzlylabs.com/article/28-fax-a-document
And here is how it's supposed to appear from your doc: https://docs.helpscout.com/article/222-use-definition-lists-for-detailed-steps#create

**Comment by shaunmcilroy** [comment]
Hey @guillaume-tgl thanks for getting in touch. The issue you're reporting is no longer occurring as of our latest [SDK release (2.0.2)](https://developer.helpscout.com/beacon-2/android/), so your best bet here would be to update to the latest version to resolve the issue. In future we'd recommend keeping tabs on the [changelog](https://github.com/helpscout/beacon-android-sdk-sample/blob/master/CHANGELOG.md) and remaining up-to-date before submitting future issues.  

If you're still seeing an issue occur on the latest version of the SDK we'll be happy to investigate further. Cheers!
