### ISSUE TITLE
Dynamic Feature Module Support

### ISSUE THREAD

**Issue by pawelqus** [helpscout/beacon-android-sdk-sample#85]
Since my application is distributed as App Bundle and supports API 16, I've made a feature module targeting devices with API 21 to support Helpscout Beacon SDK.

Unfortunately because Helpscout SDK references resources in manifest:
`hs_beacon_file_paths.xml` and `hs_beacon_searchable.xml` AAPT fails with missing resources when making a bundle.  To fix that I created an empty resources under the same name in `base` module. This works great when building stand alone APK, but when generating App Bundle, it fails with following error:
`base` and `helpscout` modules contain different content for `hs_beacon_file_paths.xml` 

Could you please help me to get it working in dynamic module?
Fixes I see is either expose `hs_beacon_searchable.xml` and `hs_beacon_file_paths.xml` so that users can copy their content to base module, or remove them from library manifest so users need to add them to app manifest if needed.

Feature module `helpscout` `build.gradle`:
```
apply plugin: 'com.android.dynamic-feature'
apply plugin: 'kotlin-android'
apply plugin: 'kotlin-kapt'
apply plugin: 'kotlin-android-extensions'

android {
    compileSdkVersion rootProject.ext.versions.compileSdk
    buildToolsVersion rootProject.ext.versions.buildTools
    

    defaultConfig {
        minSdkVersion 21
        targetSdkVersion rootProject.ext.versions.targetSdk
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    flavorDimensions "Test"
    //Empty just to make it match mobile-ui flavors
    productFlavors {
        dev {
            dimension "Test"
        }
        prod {
            dimension "Test"
        }
        debugToken {
            dimension "Test"
        }
    }
}

dependencies {
    Map deps = rootProject.ext.deps.lib

    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation project(':base')
    implementation deps.timber
    implementation deps.helpscoutCore
    implementation deps.helpscoutUI
}
```

**Comment by jotaemepereira** [comment]
Hey @pawelqus, we removed the `hs_beacon_searchable.xml` file for next versions, but will still need `hs_beacon_file_paths.xml`. Adding support API 16 is something that it is not in our plans, but let's see what we can do to help you with getting that build ready.

I created a ticket in our internal system to track this issue:https://helpscout.atlassian.net/browse/ANDSDK-373

Let me touch base with the team and I will reach out to you, thanks.

**Comment by pawelqus** [comment]
Hey @jotaemepereira, is there any chance you could expose content of `hs_beacon_file_paths.xml` for the file provider? That way I could just copy the file to `base` modle and AAPT should work fine when making the bundle.

**Comment by scottyab** [comment]
Hey @pawelqus when you say "any chance you could expose content of hs_beacon_file_paths.xml" 

Do you mean you'd like a copy of it? 

If so, that should be fine as it does not contain sensitive information but I'm reluctant to post the file here. I would recommend treating it as accessing a private API. As in it could change without warning - although this file has only changed once in the 2 years since we created it. 

Drop us an email on help@helpscout.com FOA Scott Alexander-Bown and referencing this GitHub issue and I'll send both xml files.

**Comment by pawelqus** [comment]
@scottyab Yeah, I just want to copy it to the base module hoping this will fix bundle issues and also it will not crash in runtime for API < 21 devices. I've just sent an email, thank you!

**Comment by shaunmcilroy** [comment]
Hi @pawelqus - Shaun here hopping in with @scottyab. I know we spoke over email regarding this but I wanted to touch base regarding the Beacon Android SDK for any other member of our development community who may be interested in this discussion. 

Currently, as we discussed the SDK only supports Android versions 5.0 and higher and does not presently support Dynamic Feature Modules. Our Android team spent some time investigating whether it would be possible to achieve a positive result where it may be possible, however we've not found any guidance from Google on how to effectively set up the SDK with a File Provider to work with Dynamic Feature Modules at this time.

We also observed that there are other SDKs facing similar issues in the StackOverflow issues that you'd previously supplied. While it wouldn't allow support of Android App Bundles, [an alternative solution](https://developer.android.com/training/multiple-apks/api) may be to look at creating multiple APKs for different API levels allowing you to take advantage of offering an app across multiple generations of the Android platform. It's not something we'd be able to offer specific guidance on implementing, but something that you may find useful in the interim.

Moving forward, we're not taking the possibility off the table that we'll be able to address support for Dynamic Feature Modules in the future, so we will leave this GitHub issue open and continue to track requests from the development community both here, and via email for this feature but I wanted to set clear expectations on where we are as of 4/1/20.

I can't make any promises in terms of what we will and won't take on as a company, but I have added your vote to our internal tracking tool for this request. We use that tool to manage follow-up with customers, so if we have any news to share about your request, you'll be on the list to receive an update - along with anyone who makes a request for this feature via Github.

We'll keep you updated if there's any news, and thanks again for touching base with us!

**Comment by scottyab** [comment]
As part of our regular housing keeping review, I'm closing this issue as we are not actively looking to implement this feature in the near future. Thanks for the suggestion.
