### ISSUE TITLE
Undocumented changes to PrefilledForm

### ISSUE THREAD

**Issue by tir38** [helpscout/beacon-android-sdk-sample#86]
We are upgrading from Beacon 1.0.6 to 2.0.3. Our app is no longer compiling. It looks like the constructor for `PrefilledForm` changed from:

```
/**
 *  Pre filled details for the Messaging Contact form. Ideal for saving your users time typing
 *  @param name the users name
 *  @param subject the subject of the Conversation that will be created in Help Scou
 *  @param message the message
 *  @param customFieldValues map of custom field Ids and values
 *  @param attachments a lists of Uris that will be automatically attached to the Messaging Contact form
 */
data class PreFilledForm(
        val name: String = "",
        val subject: String = "",
        val message: String = "",
        val customFieldValues: Map<Int, String> = mutableMapOf(),
        val attachments: List<String> = emptyList())

```

to

```
PreFilledForm(
    "Steve Aoki", //name
    "Need help with invoice", //subject
    "Hello, I need some help with my invoice. See attached PDF...", //message
    Collections.singletonMap(5678, "Question"), //custom field values
    Collections.singletonList("content://media/path/to/invoice"), // list of string URIs )
    "steve@aoki.com");//email address
```

I don't see where this is documented in the [CHANGELOG](https://github.com/helpscout/beacon-android-sdk-sample/blob/master/CHANGELOG.md). Will you go back and update the changelog so that other people can find this?

**Comment by aliripe** [comment]
Hey @tir38!

Thank you so much for reporting this omission in our documentation. I've already updated it to better reflect the breaking changes that were introduced with the 2.0.0 release so that no other developer runs into this problem without knowing what's causing it.

I hope that the changelog is clearer now, do let me know if you feel like that isn't the case!

**Comment by scottyab** [comment]
Hey @tir38 just to add to this in the upcoming 2.1 release we've added @JvmOverrides so that similar changes to `PreFilledForm` and `BeaconConfigOverrides` should not cause breaking changes for Apps using Java. 

Thanks again.
