### ISSUE TITLE
Links shared with customers in replies are not actionable via Previous Messages

### ISSUE THREAD

**Issue by shaunmcilroy** [helpscout/beacon-android-sdk-sample#93]
* Beacon version: 2.1.0
* Android OS version: v10
* Device make/model: Pixel 2

**Steps to reproduce**
1. Create a conversation from your Beacon via your Android device
2. Send a response from the Help Scout web-app, including a link either from the Insert Docs menu or a link wrapped around text.
..

**Actual outcome**
Beacon did not render the text as a clickable link. It's plain text only.

**Expected outcome**
Beacon should display clickable links in lieu of plain text.

**Screenshots or GIFs**
Confirmed in an SDK hosted Beacon: https://c.hlp.sc/04uPW89d
Links as seen in iOS: https://c.hlp.sc/OAubjZBe

**Comment by shaunmcilroy** [comment]
Filed on behalf of a customer. Internal link: https://helpscout.atlassian.net/browse/ANDSDK-421

**Comment by scottyab** [comment]
This issue was addressed in 2.1.1. Thanks for flagging here @shaunmcilroy

**Comment by scottyab** [comment]
As 2.1.1 has to be reverted, this was addressed in 2.1.2. Apologies for the delay updating this.
