### ISSUE TITLE
Beacon 2.1.0 deviations from Material Design

### ISSUE THREAD

**Issue by sipersso** [helpscout/beacon-android-sdk-sample#94]
There are many places where I believe the Android Beacon 2.1.0 violates design principles of material design. From HelpScouts point of view I understand that there is a point of making the interface consistent across platforms. However, I don't think this should be made at the expense of usability on each platform. Android users typically expect the app to be consistent with the platform.

Furthermore the mobile beacons appear to be a part of the host applications user flow, so following the platforms best practices will ensure that the beacons will not feel out of place in the context they are being used. 

Here are a few areas where I think that HelpScout beacon is not following material design guidelines:

1: The HelpScout Beacon does not have a up button in the top left corner when opening the beacon in neutral mode. Instead there is a close button placed in the right hand corner. This is the wrong placement for Android. A close button is fine, but it should be placed on the left side, like all other android navigation. The left icon is called navigation icon for a reason. 

Reference: Material design upward navigation
https://material.io/design/navigation/understanding-navigation.html#reverse-navigation

2: When opening the contact form there is both a close button and a back button. To be consistent with the platform there should not be multiple navigation buttons. The close button in this case is unnecessary. A back button would be enough. 

Reference: Material design upward navigation
https://material.io/design/navigation/understanding-navigation.html#reverse-navigation

3: The toolbar doesn't use elevation. This makes them look out of place and doesn't look good when content scrolls under it. 
https://material.io/components/app-bars-top#anatomy

4: Tabs should be placed either at the bottom of the appbar when using the tab component(https://material.io/components/tabs#anatomy). An alternative would be to skip the tabs altogether and use a floating action button or extended floating action button to contact support. This would have been a lot more consistent with the platform. 

5: Full screen dialog should be full screen. Mobile screens are limited in space. It doesn't make sense to provide dialogs that are not taking up the full width and height of the screen. In addition, the dialogs also have the navigation button placed in the wrong corner. Navigation on Android is on the left hand side. 
https://material.io/components/dialogs#actions.

6: The tab buttons in the title doesn't look like Android tabs. Tabs in android are text button with an underline to indicate the currently selected tab (see https://material.io/components/tabs). The helpscout tabs uses a custom design instead. The closest component is the outlined button, but these should typically be used for actions and not navigation and it is a bit confusing to use the outline as an indication of tab state. 

I realize that opinions can differ regarding design. But as a third party supplier that makes components that will be included in other apps, I personally think it is very important to follow the best practices on the respective platform to avoid confusion for the end users.

**Comment by shaunmcilroy** [comment]
Thanks for the feedback regarding the design choices made for the Beacon 2.1 SDK @sipersso 

While I don't have any data-driven responses to the points you've raised today, I'll have this logged for the team to discuss in the future. As we asked you to file this specifically to the board (in order to capture any other feedback from the development community) I'll keep this Issue open under the Question label and watch for follow up responses. 

I've also updated our customer facing teams with some guidance on keeping track of feedback regarding the implementation from our other customers, particularly around the location of the closing X and the toolbar points you raised above. If there's a conversation to be had with other folks who feel the same way regarding the points you've raised we'll definitely keep an ear to the ground and hear those out too.

Thanks for logging this @sipersso. If we have any other questions or updates to share we'll do so here on this issue.

**Comment by sipersso** [comment]
Thanks for your comment Shaun! I updated the documents with an additional comment about the tab button appearance that I missed when filing the github issue.

**Comment by jotaemepereira** [comment]
Hey @sipersso! Thanks for the thoughtful feedback and so sorry for taking so long to answer this.

About the material guides, we are aware of them, but we treat them as guidelines and not absolute rules. The SDK has a material inspired design and deviates in a few places for consistency across the product. I will answer your points one by one.

> 1: The HelpScout Beacon does not have a up button in the top left corner when opening the beacon in neutral mode. Instead there is a close button placed in the right hand corner. This is the wrong placement for Android. A close button is fine, but it should be placed on the left side, like all other android navigation. The left icon is called navigation icon for a reason.

Although we understand this request and it makes sense, we treat the X button as a way out of the Beacon, you tap on X to come back to the customer's application.

> 2: When opening the contact form there is both a close button and a back button. To be consistent with the platform there should not be multiple navigation buttons. The close button in this case is unnecessary. A back button would be enough.

This is related to my answer on the number one point, the back arrow is to go back in the SDK, but the X to go back to the customer's app, there is a difference in navigation.

> 3: The toolbar doesn't use elevation. This makes them look out of place and doesn't look good when content scrolls under it.
https://material.io/components/app-bars-top#anatomy

We agree with this, we are going to create an issue in our internal tool to track it.

> 4: Tabs should be placed either at the bottom of the appbar when using the tab component(https://material.io/components/tabs#anatomy). An alternative would be to skip the tabs altogether and use a floating action button or extended floating action button to contact support. This would have been a lot more consistent with the platform.

We are using custom tabs, that's why we did not follow Material guidelines here.

> 5: Full screen dialog should be full screen. Mobile screens are limited in space. It doesn't make sense to provide dialogs that are not taking up the full width and height of the screen. In addition, the dialogs also have the navigation button placed in the wrong corner. Navigation on Android is on the left hand side.
https://material.io/components/dialogs#actions.

This was a design decision, but we feel we can improve it, so we are going to create a card to track this.

> 6: The tab buttons in the title doesn't look like Android tabs. Tabs in android are text button with an underline to indicate the currently selected tab (see https://material.io/components/tabs). The helpscout tabs uses a custom design instead. The closest component is the outlined button, but these should typically be used for actions and not navigation and it is a bit confusing to use the outline as an indication of tab state.

This is similar to what I responded in number four, we are using custom tabs, so we did not feel to follow Material guidelines.

Thanks again for all the feedback you provide! We really appreciate it, let us know what you think, and we will keep you tune on changes.

**Comment by sipersso** [comment]
> Hey @sipersso! Thanks for the thoughtful feedback and so sorry for taking so long to answer this.
> 
> About the material guides, we are aware of them, but we treat them as guidelines and not absolute rules. The SDK has a material inspired design and deviates in a few places for consistency across the product. I will answer your points one by one.
> 
> > 1: The HelpScout Beacon does not have a up button in the top left corner when opening the beacon in neutral mode. Instead there is a close button placed in the right hand corner. This is the wrong placement for Android. A close button is fine, but it should be placed on the left side, like all other android navigation. The left icon is called navigation icon for a reason.
> 
> Although we understand this request and it makes sense, we treat the X button as a way out of the Beacon, you tap on X to come back to the customer's application.
> 

This is where I think you are getting it wrong from an end user perspective. If I look at it from my users perspective, the Beacon IS a part of my application. It is not a separate application. 

On the web, the beacon navigation makes sense as it is a popup window. In a popup it makes sense that the beacon has it's own navigation and that you have an x to close it. But if you look at it from an app perspective, there is no such thing as a window. For the end user, navigating to the support beacon will feel like navigating to a screen in the application, just as any other screen. 

> > 2: When opening the contact form there is both a close button and a back button. To be consistent with the platform there should not be multiple navigation buttons. The close button in this case is unnecessary. A back button would be enough.
> 
> This is related to my answer on the number one point, the back arrow is to go back in the SDK, but the X to go back to the customer's app, there is a difference in navigation.
> 
Again, this doesn't make sense and is based concept of windows which doesn't make sense for an app. 

> > 3: The toolbar doesn't use elevation. This makes them look out of place and doesn't look good when content scrolls under it.
> > https://material.io/components/app-bars-top#anatomy
> 
> We agree with this, we are going to create an issue in our internal tool to track it.
> 
> > 4: Tabs should be placed either at the bottom of the appbar when using the tab component(https://material.io/components/tabs#anatomy). An alternative would be to skip the tabs altogether and use a floating action button or extended floating action button to contact support. This would have been a lot more consistent with the platform.
> 
> We are using custom tabs, that's why we did not follow Material guidelines here.
> 
> > 5: Full screen dialog should be full screen. Mobile screens are limited in space. It doesn't make sense to provide dialogs that are not taking up the full width and height of the screen. In addition, the dialogs also have the navigation button placed in the wrong corner. Navigation on Android is on the left hand side.
> > https://material.io/components/dialogs#actions.
> 
> This was a design decision, but we feel we can improve it, so we are going to create a card to track this.
> 
Great!  But if you decide to go full screen the back button placement would get even more weird. Would you move the back button to the left side to be consistent with the other internal navigation? If so would you keep the X in the top right corner? Or do you consider this as another app, which you can close by clicking X to get back to the Beacon? I think this is where you get in trouble when deviating from the guidelines

> > 6: The tab buttons in the title doesn't look like Android tabs. Tabs in android are text button with an underline to indicate the currently selected tab (see https://material.io/components/tabs). The HelpScout tabs uses a custom design instead. The closest component is the outlined button, but these should typically be used for actions and not navigation and it is a bit confusing to use the outline as an indication of tab state.
> 
> This is similar to what I responded in number four, we are using custom tabs, so we did not feel to follow Material guidelines.
>
 
I noticed that your app uses white text color. This looks better. When I use the Beacon I get a black text color, and if the text is black, the tabs doesn't look like they are clickable. Looking at the documentation at https://developer.helpscout.com/beacon-2/android/#general-options I noticed that there is a color override that sets the main color, but I don't see any setting to override the title color. How did you do this?

> Thanks again for all the feedback you provide! We really appreciate it, let us know what you think, and we will keep you tune on changes.

The general theme I see with the answers is that 

1: The Beacon is viewed as a separate app rather than as an extension of the consumers application.

2: Beacon consistency between platforms (web/android/iOS) is more important than to follow what users are expecting on each platform. 

I think both these assumptions are wrong. My users won't know about HelpScout. Your Beacon is seen as a part of my app, not a separate app. And as google put it "Navigation between different screens and apps is a core part of the user experience. The following principles set a baseline for a consistent and intuitive user experience across apps". I think these principles are a good read: https://developer.android.com/guide/navigation/navigation-principles.

I think the current navigation works a lot better on the web where you have the concept of popups, and it also works resonable well on iOS where you have the concept of modal windows and separate navigation stacks. But in my opinion it doesn't translate well to Android.

**Comment by sipersso** [comment]
Ok, then I at least know what to expect and I won’t post any more design feedback. 

For the record, the visual look is great. It is just the navigation and usability on Android that I have problems with. This could easily have been corrected by placing the back button in the left corner and skipping the X button. If you did this, the beacon would still be consistent with your design AND behave the way Android users expect.

**Comment by bohemima** [comment]
I agree wholeheartedly with @sipersso on this issue. Especially when it comes to navigation.

**Comment by shaunmcilroy** [comment]
Hey @bohemima - happy to accept feedback from all developers! If you are currently using the beta version of the SDK we'd love to capture your thoughts. Can you expand on your note above with regards to navigation (and any other areas)? 

Thanks.

**Comment by bohemima** [comment]
@shaunmcilroy we're currently in the market for something to integrate, this issue caught my eyes, after som testing I found navigation to be confusing in many aspects.

* Android back navigation and Beacon back button does not always do the same thing
* Beacon back button not taking you back to where you were
* The use of a close button is confusing, for OUR users the help system / contact is a part of the app, not a separate app (at least on mobile)
* Reading an article should preferably open within the main area, not inside a popup (some of our users are still using older phones with significant less screen size) This screen, regardless of the what I think of it is the _only_ screen that correctly warrants a close button.

**Comment by shaunmcilroy** [comment]
@bohemima Thank you for the feedback and glad to hear you're exploring options! We're capturing the information shared here for our design team to consider so I definitely recommend following the repo for any future updates. I must be clear however that there's no ETA on when, if any, of the changes requested above will be implemented. 

For now our internal roadmap is progressing by way of using the design language and implementation available today, but if that changes we'll be sure to loop you into the conversation. If you have any other questions about the SDK, or if you discover anything separate to the 2.1.0 UX please let us know by opening a new issue.

**Comment by sipersso** [comment]
> * Android back navigation and Beacon back button does not always do the same thing
> * Beacon back button not taking you back to where you were

Regardless of the design choices.... these two are bugs right? I'd say these two are separate issues from the general design feedback I have posted about here.

**Comment by shaunmcilroy** [comment]
- Beacon back button not taking you back to where you were
@bohemima @sipersso that has been logged for our team here. Thanks for reporting: https://github.com/helpscout/beacon-android-sdk-sample/issues/100

- Android back navigation and Beacon back button does not always do the same thing
Can you elaborate further on this feedback point? If you feel there's an issue which is outside of any _Material Design_ considerations please create a new issue speaking specifically to the functionality of the back navigation options vs the Beacon options. Thanks!

**Comment by sipersso** [comment]
I guess what @bohemima is referring to is the same as the bug I reported in #95 (#100)? In this case the toolbar up button does not behave the same(first point) as the device back and the navigation back does not take you back to the previous state (second point)

**Comment by adrianne-helpscout** [comment]
We have had further discussions and investigations as a team in regard to the feedback about full-screen for reading articles (https://helpscout.atlassian.net/browse/ANDSDK-461) and we just wanted to close the loop and let you know that we will be leaving things as they are currently designed. 

The other issue around toolbar elevation (https://helpscout.atlassian.net/browse/ANDSDK-467) is still under consideration.

**Comment by shaunmcilroy** [comment]
Hey @sipersso -- With the release of 2.2.1 this morning we've made sure that Toolbars now have an elevation so that when content scrolls beneath them the user experience is better as it's easier to tell where the Toolbar ends and the scrolling content begins. 

Check out the rest of the changelog here: https://github.com/helpscout/beacon-android-sdk-sample/blob/master/CHANGELOG.md

Thanks for logging this item -- have a great day!

**Comment by sipersso** [comment]
Thanks! The toolbar elevation was probably the least important part in my list, but I'll check it out. The most important issue here is regarding navigation and confusing back button behavior. 

If you want an example of where inconsistent back navigation leads to usability problems you can check out this screen: 
![back_button](https://user-images.githubusercontent.com/6479433/92608363-8c981180-f2b5-11ea-9ec0-b60820548979.png)

Here you have a back button, an X and a "return home".  Three back buttons in one screen, each leading to different destinations.

**Comment by sipersso** [comment]
Just tested... and the elevation looks good!
