### ISSUE TITLE
Problems with ProGuard obfuscation

### ISSUE THREAD

**Issue by JMPergar** [helpscout/beacon-android-sdk-sample#96]
We’ve integrate Android SDK in our app and all works in correct way until we activate obfuscation. In documentation we don’t see any ProGuard rule needed to include. is HelpScout Android SDK compatible with obfuscation with ProGuard?

**Comment by scottyab** [comment]
Hi @JMPergar, Yes the HelpScout Android SDK should be compatible with ProGuard/R8. There aren't any explicit rules noted in the documentation as they included in the proguard.txt in the AAR files. 

Is the issue compile-time or runtime? it would help if you could share the error message or stack trace you're seeing? if you'd rather share that privately please email help@helpscout.com FOA Scott Alexander-Bown and I'll investigate. 

One thing to note is that we are using R8, are you explicitly using ProGuard? `useProguard = true`? or have you migrated to R8?

**Comment by JMPergar** [comment]
Is in runtime and we are using R8.

These are the lines that I've managed to find in the log:

![Captura de pantalla 2020-05-27 a las 16 14 25](https://user-images.githubusercontent.com/2472301/83031797-518b0e80-a035-11ea-9628-f84fee6e7cc9.png)

**Comment by JMPergar** [comment]
This is the response in the app:

![photo5942570197774873269](https://user-images.githubusercontent.com/2472301/83032300-f1489c80-a035-11ea-8cb9-43805492b454.jpg)

**Comment by scottyab** [comment]
Thanks for that @JMPergar , it appears Beacon is initialising successfully (i.e no crashing) but there's an error on the HomeActivity? but it's not clear what that is from the log messages. I've not seen `activityResumeTrigger: not whiteListed error` before 🤔 . I have a few questions... 

The release buildtype of the [Kotlin Sample app](https://github.com/helpscout/beacon-android-sdk-sample/tree/master/sample-kotlin) in this repository is [minifyEnabled](https://github.com/helpscout/beacon-android-sdk-sample/blob/master/sample-kotlin/build.gradle#L37). 
1) If you clone/download Kotlin Sample and add your Beacon Id and deploy to your device are you seeing it work ok? 

2) Can you enable logs on the Beacon SDK and then see if we can get some of the surrounding log messages as I really need more details on the crash to effectively debug this.  

```
Beacon.Builder()
                .withBeaconId("Your Beacon Id")
                .withLogsEnabled(true)
                .build()
```

Googling the log message I see a couple of references to ReativeNative and Unity apps. 
3) are you developing a regular Android app or using a cross-platform solution? 

4) How are you launching the Beacon? i.e `BeaconActivity.open(context)`

Thanks, 
Scott

**Comment by oscarcpozas** [comment]
Hey Scott,

I'm Óscar, @JMPergar's co-worker. We've been seeing that the problem was derived from using the [proguard-android-optimize](https://android.googlesource.com/platform/sdk/+/master/files/proguard-android-optimize.txt) rules to configure Proguard instead [proguard-android](https://android.googlesource.com/platform/sdk/+/master/files/proguard-android.txt). That file add these extra rules:

```
-optimizations !code/simplification/arithmetic,!code/simplification/cast,!field/*,!class/merging/*
-optimizationpasses 5
-allowaccessmodification
-dontpreverify
```

We've chosen to disable these optimizations, thank you for your help ❤️

**Comment by scottyab** [comment]
Hey @oscarcpozas @JMPergar thanks for getting back to me. Happy you're seeing everything working 🎉 . Feel free to raise another issue if you require any further assistance. Also just FYI we're planning to release SDK v2.1.1 soon.
